### ISSUE TITLE
Intégration du travail réalisé sur mviewer template

### ISSUE THREAD

**Issue by bchartier** [mviewer/mviewerstudio#100]
@Agath21 a réalisé des patrons de templates mustache et des supports pédagogiques pour faciliter la mise en forme des fiches d'information dans les cartes mviewer. Quand ces supports seront mis en ligne il faudrait voir de quelle manière mviewer studio pourrait bénéficier de cela.

**Comment by spelhate** [comment]
Ressources disponibles :

- Code source des templates créés : https://github.com/geobretagne/mviewer/tree/master/demo/mviewer_templates
- Application mviewer qui mobilise ces templates : https://geobretagne.fr/mviewer/?config=/apps/tutoriel/templates/config_template.xml

**Comment by lecault** [comment]
Je ferme, le générateur de template remplira ce besoin.
