### ISSUE TITLE
majeur - Nettoyage des branches

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#112]
Je viens de comparer les branches en cours suite à #111.

Le dernier commit commun entre develop et master est le suivant : 759975c7f2943f308c1488b458441785d006d7a7

Il y a pas mal de commit sur develop qui ne sont pas sur master. Ca vaudrait le coup de faire une release @bchartier ?

Voici les étapes à suivre  : 

1. passer les commits > au 759975c7f2943f308c1488b458441785d006d7a7 du 06/03/2021 de master à develop (via la commande cherry-pick). Les commits master qui ne sont pas dans develop ne sont pas énormes ca devrait être largement gérable. Utiliser la commande `push -f` pour pousser les modifs sur develop (on a modifié l'arbre...)
2. developp contenant les commits, on revient sur le commit Le dernier commit commun entre develop et master est le suivant : https://github.com/geobretagne/mviewerstudio/commit/759975c7f2943f308c1488b458441785d006d7a7
 via un `reset --hard 759975c7f2943f308c1488b458441785d006d7a7 && push -f` 
3. gérer la PR #110 en ciblant developp
4.  nouvelle version (si souhaité)

**Comment by Gaetanbrl** [comment]
Dispo sur https://github.com/Gaetanbrl/mviewerstudio/tree/master

- [ ] cherry-pick master vers develop pour commits > 759975c7f2943f308c1488b458441785d006d7a7
- [ ] roll back branche master pour se positionner sur commit 759975c7f2943f308c1488b458441785d006d7a7
- [ ] changer branche cible #110 vers develop
- [ ] new release

**Comment by Gaetanbrl** [comment]
@lecault peux-tu vérifier les infos du config-sample.json suivant ? 
https://github.com/Gaetanbrl/mviewerstudio/blob/develop/config-sample.json

**Comment by lecault** [comment]
Il est pas à jour vis à vis du master (notamment les scan ign).

Je pense qu'il faut migrer le fichier du master vers develop ?

**Comment by Gaetanbrl** [comment]
j'ai fait les cherry-pick entre master et develop, normalement les infos de master sont dans develop.
**Comment vois-tu qu'il n'est pas à jour ?**

Il faut comparer le config-sample.json de la branche master de geobretagne avec le même fichier de la branche develop de mon dépôt :

https://github.com/geobretagne/mviewerstudio/blob/master/config-sample.json
et
https://github.com/Gaetanbrl/mviewerstudio/blob/develop/config-sample.json

L'objectif est de conserver tous les commits de master et de les migrer vers develop pour ne pas écraser de modifications qui pourrait être dans develop qu'on aurait pas mis dans master.

**Comment by Gaetanbrl** [comment]
> Il est pas à jour vis à vis du master (notamment les scan ign).

Le scan ign c'est plan_ign ?

**Comment by Gaetanbrl** [comment]
@lecault dans le fichier https://github.com/Gaetanbrl/mviewerstudio/blob/develop/config-sample.json

il y a ces 3 paramètre qui ne sont pas dans master : 

        "delete_service": "srv/delete.php",
        "list_service": "srv/list.php",
        "store_style_service": "srv/store/style.php",


Je pense que ca a été apporté dans develop et pas dans master, donc on ne peut pas juste écraser le fichier en remplaçant celui de develop par celui master.

**Comment by lecault** [comment]
Hum faudra que je prenne le temps de regarder. L'idée est de mettre nickel sur develop puis de pousser sur master ?

**Comment by Gaetanbrl** [comment]
> L'idée est de mettre nickel sur develop puis de pousser sur master ?

Oui car les merge entre la branche developp et master on ramenés des commits qui ne sont pas dans develop.

Comme je le précisais, seuls les commits qui sont après ce commit 759975c7f2943f308c1488b458441785d006d7a7sont à passer dans develop (donc seuls les commits après le 6 mars)

**Comment by bchartier** [comment]
Je suis dispo aujourd'hui pour travailler sur ce ticket.

**Comment by bchartier** [comment]
> Il y a pas mal de commit sur develop qui ne sont pas sur master. Ca vaudrait le coup de faire une release @bchartier ?

Oui, cela vaudrait le coup.
L'idéal serait de faire une release sans les modifs de @HWFord histoire de laisser le temps de tester ces modifs et d'apporter tranquillement des modifs/corrections si besoin d'ici une prochaine release.

**Comment by bchartier** [comment]
> Comme je le précisais, seuls les commits qui sont après ce commit [759975c](https://github.com/geobretagne/mviewerstudio/commit/759975c7f2943f308c1488b458441785d006d7a7) sont à passer dans develop (donc seuls les commits après le 6 mars)

J'ai intégré la PR #113 dans la branche `develop`.

**Comment by Gaetanbrl** [comment]
> L'idéal serait de faire une release sans les modifs de @HWFord 

Parfait

**Comment by bchartier** [comment]
> > L'idéal serait de faire une release sans les modifs de @HWFord
> 
> Parfait

Pour la release, on avait défini des règles de numérotation ? On doit garder la cohérence avec la dernière release de mviewer ?

**Comment by Gaetanbrl** [comment]
> Pour la release, on avait défini des règles de numérotation ?

Ca ne me parle pas.

>  On doit garder la cohérence avec la dernière release de mviewer ?

Pour le code / dépendance oui. Mais on peut avoir une numérotation indépendante pour mviewer studio.

D'ailleurs je ne sais pas s'il y a une question de dépendance dans le readme mviewer ou mviewer studio pour indiquer que telle version studio est valable pour telle version mviewer ?

**Comment by Gaetanbrl** [comment]
@bchartier merci pour le merge.
Est-ce que je peux faire le roll back pour faire revenir la branche master sur le commit (comme dernier commit) 759975c7f2943f308c1488b458441785d006d7a7 ?

**Comment by bchartier** [comment]
> > Pour la release, on avait défini des règles de numérotation ?
> 
> Ca ne me parle pas.
> 
> > On doit garder la cohérence avec la dernière release de mviewer ?
> 
> Pour le code / dépendance oui. Mais on peut avoir une numérotation indépendante pour mviewer studio.

ok

> D'ailleurs je ne sais pas s'il y a une question de dépendance dans le readme mviewer ou mviewer studio pour indiquer que telle version studio est valable pour telle version mviewer ?

On a une dépendance car mviewer studio crée un fichier de config pour mviewer mais on ne documente cette dépendance entre versions nulle part je crois. On devrait en parler lors de la prochaine réunion du comité de pilotage à mon avis.

**Comment by bchartier** [comment]
> @bchartier merci pour le merge.
> Est-ce que je peux faire le roll back pour faire revenir la branche master sur le commit (comme dernier commit) [759975c](https://github.com/geobretagne/mviewerstudio/commit/759975c7f2943f308c1488b458441785d006d7a7) ?

Logiquement master devrait pointé sur le dernier commit de la dernière release, non ?
genre : e580fff

**Comment by bchartier** [comment]
> > > On doit garder la cohérence avec la dernière release de mviewer ?
> > 
> > 
> > Pour le code / dépendance oui. Mais on peut avoir une numérotation indépendante pour mviewer studio.
> 
> ok

J'ai créé un milestone 3.2 avec quelques tickets/pull requests associés :
https://github.com/geobretagne/mviewerstudio/milestone/2
Merci de me signaler si je dois ajouter d'autres choses en vue de la release 3.2.

**Comment by bchartier** [comment]
> > @bchartier merci pour le merge.
> > Est-ce que je peux faire le roll back pour faire revenir la branche master sur le commit (comme dernier commit) [759975c](https://github.com/geobretagne/mviewerstudio/commit/759975c7f2943f308c1488b458441785d006d7a7) ?
> 
> Logiquement master devrait pointer sur le dernier commit de la dernière release, non ?
> genre : [e580fff](https://github.com/geobretagne/mviewerstudio/commit/e580fffcf7d823f45f468eb54b44969af262b4a6)

J'ai sans doute raison en théorie mais en fait je pense qu'on a intérêt à ne pas toucher master tant que la release 3.2 n'a pas été validée.
Ça vous semble raisonnable ?

**Comment by lecault** [comment]
> @lecault dans le fichier https://github.com/Gaetanbrl/mviewerstudio/blob/develop/config-sample.json
> 
> il y a ces 3 paramètre qui ne sont pas dans master :
> 
> https://github.com/Gaetanbrl/mviewerstudio/blob/62896ca09d0d9f83d3206ac66b48a2d58d5e6bce/config-sample.json#L4-L6
> 
> Je pense que ca a été apporté dans develop et pas dans master, donc on ne peut pas juste écraser le fichier en remplaçant celui de develop par celui master.

Effectivement il y a juste une différence sur ces 3 lignes sinon c'est juste des espaces / tabulations qui changent.
Ces 3 fichiers sont présents dans le master et dans develop à un autre endroit.

C'est lié à la conf GeOrchestra.

Un niveau a été ajouté, il faudrait mettre : 

        "upload_service": "srv/php/store.php",
        "delete_service": "srv/php/delete.php",
        "list_service": "srv/php/list.php",
        "store_style_service": "srv/phpstore/style.php",

**Comment by spelhate** [comment]
Je viens de merger develop dans master.
La CI pour fabriquer les images docker fonctionne bien maintenant 
![image](https://user-images.githubusercontent.com/1793792/150377779-c8905003-0d5f-468d-ae12-0fe393a009b5.png)
Merci @pierrejego @bchartier @lecault @Gaetanbrl
