### ISSUE TITLE
Docs - ajouter une page dans la doc sur les contributions

### ISSUE THREAD

**Issue by bchartier** [mviewer/mviewerstudio#116]
Décrire l'organisation :
* branches (master, develop...)
* pullrequest
* release : numérotation, compatibilité avec mviewer, changelog
* commits
* ...

**Comment by Gaetanbrl** [comment]
Ce serait une solution simple et facile.
Pas de docs spécifique mviewer studio de prévue ?

**Comment by lecault** [comment]
si on a commencé à travailler dessus : https://mviewerstudio.readthedocs.io/fr/doc/
