### ISSUE TITLE
Incohérence zoom fenêtre options de la carte / carte

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#142]
Dans mviewerstudio, on remarque une incohérence entre le zoom choisi dans la fenêtre Options de la carte :

![image](https://user-images.githubusercontent.com/5269430/205931477-ec54a441-b1da-4616-abfe-ebee835f7cfc.png)

Et celui de la carte générée : 

![image](https://user-images.githubusercontent.com/5269430/205931583-380432cb-4a34-400f-851e-05fa25cb3775.png)

**Solution proposée** 

Serait t'il possible que le zoom de la carte générée soit augmenté de 1 ? Par défaut passage de z=7 = z=8.

Par défaut on a ça : https://gis.jdev.fr/mviewer/?x=-307904&y=6141345&z=7&l=&lb=positron&config=apps/bdfd5c7904ac9844208b2f489edc16b2.xml&mode=d

Et on devrait avoir ça : https://gis.jdev.fr/mviewer/?x=-307904&y=6141345&z=8&l=&lb=positron&config=apps/bdfd5c7904ac9844208b2f489edc16b2.xml&mode=d

Merci !

**Comment by LPoin** [comment]
Bonjour @lecault, les exemples de la solution proposée ne fonctionnent plus; est-il possible de les refaire ? Merci.

**Comment by lecault** [comment]
Un gif pour illustrer la différence de zoom : 

![zoom](https://github.com/user-attachments/assets/478a7734-50cd-4d5f-b462-0a9299e8f897)

**Comment by LPoin** [comment]
Le problème a été indentifié : le zoom reste cohérent avec la séléction mais l'écran de la map est plus étendu. On peut donc voir au delà de la sélection intiale dans le studio.

Solution : surcharger le center et le zoom avec une bbox. Ce paramètre sera optionnel coté mviewer mais toujours envoyé si on passe par le studio. Ainsi la map affichée correspondra à la sélection dans les options de la map mais ne provoquera pas de problème pour les utilisateurs mviewer.

Je pars sur cette solution, n'hésitez pas à revenir vers moi si il y a des questions ou des suggestions.

**Comment by LPoin** [comment]
Issue coté mviewer -> https://github.com/mviewer/mviewer/issues/918

**Comment by LPoin** [comment]
PR en attente de review -> https://github.com/mviewer/mviewerstudio/pull/312
