### ISSUE TITLE
Module Thématiques & données - Gestion de l'affichage par défaut des thématiques et couches

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewerstudio#146]
# Module Thématiques & données - Gestion de l'affichage par défaut des thématiques et couches

## Thématique : Déroulée par défaut 
Dans la version actuelle, pour ouvrir une thématique lors du démarrage de l'application, il faut cocher le bouton suivant : 
![image](https://user-images.githubusercontent.com/22764056/206210664-beeca163-b98e-4028-b644-7602cbe35ae4.png)

Pour optimiser l'utilisation de ce paramètre, un bouton pourrait être ajouté à côte de "Déplacer" dans le panneau des thématiques afin d'activer ou non "Déroulé par défaut". 
![image](https://user-images.githubusercontent.com/22764056/206212842-af37df04-fc22-43c1-858a-54602405f90e.png)

De plus, le mviewer permet d'ouvrir une seule thématique lors du démarrage, il est donc nécessaire de gérer cette condition en autorisant un seul bouton "Déroulé par défaut" actif pour l'ensemble des thématiques (non géré actuellement). 

## Couche : Affichée par défaut 

Dans le même esprit, il pourrait être envisageable d'ajouter dans la liste des couches un bouton pour activer les couches visibles au démarrage.

**Comment by lecault** [comment]
Fait dans l'issue #324
