### ISSUE TITLE
ERROR CI - build image docker 

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#155]
Il semble que l'action pour builder l'image Docker échoue.
Idem en local lorsqu'on suit les instructions d'installation du backend python, on obtient : 

> [ImportError: cannot import name 'escape' from 'jinja2'](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2)

Le problème provient de la version de Jinja qui ne contient plus `Escape`.

L'installation d'une version `Flask>=2` semble corriger le problème.

**Comment by Gaetanbrl** [comment]
> ref commit https://github.com/mviewer/mviewerstudio/commit/5cfb22dea16c5e8676105f51f18a9f12aee9f205

Je viens de modifier la version Flask dans les dépendances.

https://github.com/mviewer/mviewerstudio/blob/5cfb22dea16c5e8676105f51f18a9f12aee9f205/srv/python/requirements.txt#L1

- [ ] L'image docker build
- [ ] En local on peut lancer flask

**ATTENTION : en l'état on ne peut pas utiliser les PHP en lancant le mode dev flask-run (les appels échouent donc).**

Je n'ai pas été plus loin dans les tests...


@spelhate @bchartier @lecault

**Comment by spelhate** [comment]
Bonjour,
Je viens de tester la composition docker qui combine (nginx + mviewer + studio) à la racine du projet et j'ai un truc qui se lance sans erreur. Je n'ai pas poussé les tests plus loin.
