### ISSUE TITLE
MEG - Refonte du système de sauvegarde des fichiers de configuration

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#158]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Histoire

**En tant que** utilisateur,
**Je souhaite** pouvoir utiliser différente version d'une configuration dans mviewerstudio
**Pour** pouvoir rechercher une version, revenir à une version ultérieure ou plus récente, supprimer une version, supprimer une application, taguer une application

## Description détaillée

Actuellement, les sauvegardes mviewerstudio consistent en la sauvegarde du fichier de configuration (config.xml) sur le serveur dans un répertoire dédié. Chaque enregistrement génère la création d’un nouveau fichier (hachage md5). Il est ainsi presque impossible pour un utilisateur de revenir à une version particulière de l’application.
 
Il est donc nécessaire de **refondre** le système de sauvegarde et de prévisualisation, afin que les utilisateurs puissent pour une application mviewer particulière :

- Visualiser les applications de l’organisation dans leur dernière version (recherche par mot clé, titre de l’application) ;
- Possibilité de restaurer une version précédente (recherche par date, par statut) pour chaque application ;
- Possibilité de supprimer une application et ses versions ;
- Affecter un statut à l’application (brouillon, publié).

# Solution proposée

Actuellement, les cartes sont représentées par un fichier XML toutes stockées dans le répertoire `/store`.

## Solution fonctionnelle

Des éléments d'interface seront ajouter dans l'UI de mviewerstudio fin de pouvoir changer de version.

**(maquette à proposer)**

## Solution technique

Nous proposons d'utiliser GitPython pour gérer le versionnement d'une config XML :

https://gitpython.readthedocs.io/en/stable/intro.html#requirements

Il faudra donc isoler les cartes pour trouver dans le répertoire `/store`, 1 seul et unique répertoire par carte.

Chaque répertoire contiendra un `.git` pour pouvoir utiliser le système de versionnement de Git.

Concrètement, lorsqu'on cliquera sur "Créer une carte", un script Python permettra de créer un répertoire unique qui sera en réalité un nouveau dépôt git contenant la config XML.

Avec deux cartes, l'arborescence serait par exemple la suivante : 

```
/srv/python/store
└── carte1
   └── config_carte1.xml
   └── .git
└── carte2
    └── config_carte2.xml
    └── .git
```

Avec ce système, il sera possible de rechercher des cartes en respectant une règles de nommage contenant un horodatage et un nom du type : 

`09302001012022-LAND_COVER_2023`➔ `HHmmSSYYYYMMDD-NOM`

L'outil GitPython permettra pour sa part d'utiliser Git pour manipuler les versions et notamment :

- Créer une carte et la version de démarrage > création d'un repo > Par défaut sur la branche `main`
- Faire une nouvelle version > Création d'une branche horodatée
- Changer de version > Changer de branche
- Supprimer une version > Suppression d'une branche
- Suppression d'une carte > Suppression d'un répertoire
- Ajouter une catégorie type brouillon > Ajout d'un tag "brouillon"
- Ajouter des mots clés > Ajouter dans le tag les mots clés
- Rechercher une version > Lister les tags et rechercher dans leur nom
- etc.

Cette mécanique se veut simple par l'utilisation d'un système de versionnement simple **sans base de données**, en réutilisant uniquement le système d'indexation des changements de git.

Cet outil propose également d'utiliser directement Git si des fonctionnalités n'étaient pas inclues dans GitPython.

## Suite au point du 10/02/2023

Pour la recherche globale dans toutes les cartes, il est indiqué : 

> Visualiser les applications de l’organisation dans leur dernière version (recherche par mot clé, titre de l’application) ;

Pour ce faire, nous proposons d'utiliser un fichier type JSON ou une base de données portable (type sqLite) qui fera office de registre des métadonnées de carte (uniquement utilisé pour cet usage de registre et la recherche global). Ce type de registre facilitera le recensement des carte disponibles d'une instance et leur recherche, notamment d'un point de vue performance.

La recherche se fera aussi dans toutes les informations des champs DECAT.
Par exemple, pour retrouver une carte par créateur, il faudra alors saisir le nom du créateur sans action supplémentaire. Ce sera identique pour les autres champs DECAT de la config XML.

Les métadonnées d'une carte correspondent aux balise `<dc>`  gérées dans mviewer correspondant au format DCAT :
https://doc.data.gouv.fr/moissonnage/dcat/

Une balise `<dc:keyword>` sera ajoutée également pour la recherche pas mots clé.

**@spelhate @lecault, après relecture  du CCTP, il n'est pas demande de limiter l'affichage des cartes selon l'utilisateur connecter. Bien que ce soit réalisable, ce point n'est pas inclus / traité dans cette issue (hors scope).**

**Comment by Gaetanbrl** [comment]
lié à #156

**Comment by spelhate** [comment]
> * Supprimer une version > Suppression d'un répertoire

C'est plutôt ici suppression d'une branche non ?

**Comment by spelhate** [comment]
Cette évolution ne sera donc pas compatible PHP (lib Python). Est-ce qu'il faut rendre cette évolution optionnelle via config  ex :

- `mode_sauvegarde="git"` 
- `mode_sauvegarde="file"`

 pour ne pas casser l'existant ?

**Comment by spelhate** [comment]
> Avec ce système, il sera possible de rechercher des cartes en respectant une règles de nommage contenant un horodatage et un nom du type :
> 
> `09302001012022-LAND_COVER_2023`➔ `HHmmSSYYYYMMDD-NOM`

Ca ne semble pas facile à utiliser (HHmmSS)

**Comment by spelhate** [comment]
> * Ajouter une catégorie type brouillon > Ajout d'un tag "brouillon"

Pour moi, le tag brouillon doit être affecté à la carte et pas à une ou plusieurs versions de la carte ? qu'en penses-tu @lecault ?

**Comment by bchartier** [comment]
Remarque générale perso : créer un dépôt Git pour juste une carte ça me paraît surdimensionné mais bon c'est vrai que sur le papier ça fait le boulot.
L'usage de Git est intéressant mais j'ai l'impression qu'on monte d'un sacré cran en complexité.
Ça veut aussi dire qu'on passe doit passer par Git si on touche à des fichiers sans passer par studio.
Perso, j'aurais tendance à dire que ce genre d'évolution devrait être discuté et maturé avant de se lancer (passage en comité de pilotage peut-être).

**Comment by pierrejego** [comment]
De mon point de vue ça reste assez léger car ce n'est pas un dépôt Git avec un remote. Tout reste côté client, c'est juste pour l'utilisation de l'historisation, mais si le répertoire est supprimé tout est supprimé.

**Comment by pierrejego** [comment]
Mais oui c'est sur il faut que vous en parliez en PSC

**Comment by Gaetanbrl** [comment]
> Ça veut aussi dire qu'on passe doit passer par Git si on touche à des fichiers sans passer par studio.

y a surement moyen de faire un status au démarrage et de voir s'il y a des changements : 
- faire une nouvelle branche (checkout -b) et passer sur cette branche / ou faire un push  via le script (peu importe en réalité).
- L'état avant la modification manuelle restera connu vu que ca aura été une branche précédente

L'idée est que ca reste transparent par l'utilisateur.

Je me demande même si ce serait pas plus simple d'importe sa config via l'IHM et pas passer par le serveur. Si on utilise studio autant passer par studio sinon je vois pas l'intérêt...

**Comment by lecault** [comment]
> > * Ajouter une catégorie type brouillon > Ajout d'un tag "brouillon"
> 
> Pour moi, le tag brouillon doit être affecté à la carte et pas à une ou plusieurs versions de la carte ? qu'en penses-tu @lecault ?

Oui, pour moi par défaut on est en brouillon et c'est cette issue #161 qui matérialise le changement de statut.

**Comment by Gaetanbrl** [comment]
> c'est cette issue https://github.com/mviewer/mviewerstudio/issues/161 qui matérialise le changement de statut

Oui, la gestion du passage en production sera traité dans l'issue spécifique

**Comment by Gaetanbrl** [comment]
Routes (a valider / adapter) à détailler dans un Swagger approprié :

- Ajouter une version (calculée sur la dernière valeur <int>)

> <POST> /srv/version/<id_config>

`http://localhost:5000/srv/version/05bb190f58b9/`

- Changer de version

> <POST> /srv/version/change/<id_config>/<version>

Paramètre (`optionnel`) : `as_new <bool>` pour repartir d'une version ciblée comme version courante si `true`.

`http://localhost:5000/srv/version/change/05bb190f58b9/2?as_new=true`

- Supprimer toutes les versions (sauf version courante) :

> <DELETE> /srv/version/<id_config>

`http://localhost:5000/srv/version/05bb190f58b9`

- Supprimer une version spécifique

> <DELETE> /srv/version/<id_config>/<version>

`http://localhost:5000/srv/version/05bb190f58b9/1`

**Comment by Agath21** [comment]
## Exemple de cas d'utilisation 

1 – Je créer une application et je débute la configuration de l’application : 
![image](https://user-images.githubusercontent.com/22764056/223494287-ac187a25-5a8e-406a-8ce2-2e831f4b37b7.png)

2 – J’accède à l’historique des modifications en mode avancée via « Options ». Cela me permet de visualiser l’évolution de mon travail. A chaque fois que j’ai cliqué sur « Enregistrer », cela a créer une ligne dans le tableau avec un état de modification. 
![image](https://user-images.githubusercontent.com/22764056/223494358-ea936f74-faf7-4039-aff7-23037bb36ef9.png)


3 – Je souhaite signaler un état particulier de l’avancement de mon travail. Pour cela, je crée une étiquette en cliquant sur « Marquer cet état » avec une description particulière : 
![image](https://user-images.githubusercontent.com/22764056/223494405-88e5b146-c982-4c35-a2ee-ce0e3066afcb.png)

4 – J’ai donc créer une nouvelle étiquette indiquant « Paramétrage de l’app » : 
![image](https://user-images.githubusercontent.com/22764056/223494433-1737adad-771e-4494-bcfa-00fc721ba952.png)

5 – Je réalise de nouveau des modifications. J’ajoute une nouvelle couche de données « Lycées en Bretagne » et je souhaite marquer un nouvel état :
![image](https://user-images.githubusercontent.com/22764056/223494477-2ed7586d-2cc4-4537-9016-504fd04465cb.png)

## Gestion des versions
Pour gérer mes versions, je peux réaliser plusieurs actions : 
- Voir exclusivement les version étiquetées 
![image](https://user-images.githubusercontent.com/22764056/223494735-92faae9a-947b-4029-b898-787b6f6482b7.png)

- Rechercher une version à l’aide de la barre de recherche 
- Prévisualiser une version antérieure à l’aide de l’oeil
- Restaurer l’application à une version antérieure à l’aide de la flèche. Une modale permet de valider une seconde fois la restauration : 
![image](https://user-images.githubusercontent.com/22764056/223494963-dcc32a42-09de-4af0-ae3c-56b78997c193.png)

Je peux également gérer l’ordre d’affichage des versions avec les entêtes du tableau et le système de pagination :
![image](https://user-images.githubusercontent.com/22764056/223495051-9eaf0034-a110-4c38-b87c-7fb77171a72a.png)

**Comment by lecault** [comment]
Vu avec Gaëtan : Je lance la création d'une application et je clique sur prévisualiser. Le système me renvoie une erreur.
=> Erreur du au fait que l'application n'a pas été enregistrée auparavant.

Solution : avoir un message d'alerte si clic sur prévisualiser si non enregistré auparavant.

**Comment by lecault** [comment]
Premiers retours rapides : 

- Il faudrait que le bouton Supprimer soit visible en mode simple
- Mettre un message lorsqu'on clique sur supprimer (êtes vous certain de supprimer cette application) : c'est actuellement violent, il supprime directement l'application.
- D'ailleurs il semble supprimer l'application de la liste des applications de l'user Mais pas les fichiers dans /store
- Régulièrement quand je veux consulter les modifications, ça ne s'affiche pas : 

![image](https://user-images.githubusercontent.com/5269430/223753231-7b7ba55c-6e94-4cc7-99d5-a350404c98d6.png)

**Comment by Gaetanbrl** [comment]
> Premiers retours rapides :

A compléter avec des étapes pour reproduire (pas à pas) si possible @lecault :)

**Comment by Gaetanbrl** [comment]
> il semble supprimer l'application de la liste des applications de l'user Mais pas les fichiers dans /store

J'ai reproduis. J'ai push des modifications sur les routes.

Par contre je constate que derrière georchestra (ou avec gunicorn ?), les requêtes types DELETE retournent une 400 : 

```
URL de requête: https://gis.jdev.fr/mviewerstudio/api/app
Mode de requête: DELETE
Code d'état: 400 
```
**Retour :** 
```
description: "The browser (or proxy) sent a request that this server could not understand."
name: "Bad Request"
```

**Pas de soucis avec flask en dev.**

**Comment by Agath21** [comment]
### Corrections à réaliser :

- [ ] Modifier l'emplacement du bouton supprimer. Après un premier enregistrement, le bouton "supprimer" prend l'emplacement de "enregistrer" -> Potentielle erreur de manipulation (double clique) pour les "cliqueurs fous" ... 
- [ ] Ajouter une fenêtre de validation supplémentaire lors de la suppression d'une app

**Comment by spelhate** [comment]
Quel système proposez-vous pour , je reprends ce qu'il y a dans le CCTP "Visualiser les applications de l’organisation" ?

**Comment by Gaetanbrl** [comment]
Je vois que les spécifications indiquent : 

> Visualiser les applications de l’organisation dans leur dernière version (recherche par mot clé, titre de l’application) ;

La recherche par saisie libre actuelle devra donc permettre de rechercher par nom d'organisation également (l'organisation étant disponible dans le XML via cette issue) :

![image](https://user-images.githubusercontent.com/16317988/225642577-99e6eb40-312c-41a9-90d0-01a8f8e3ee15.png)

Est-ce bon pour vous @lecault @spelhate ?

**Comment by spelhate** [comment]
Si je comprends bien, il faudra saisir une partie du nom de l'organisation ?
On verra également les applications de l'organisation créées par un autre utilisateur de cette même organisation ?
Quel comportement en mode non connecté ?

**Comment by Gaetanbrl** [comment]
> Le besoin suivant a été précisé par @spelhate et @lecault (échange via Element)

La phrase suivante du CCTP : 

> Visualiser les applications de l’organisation

... a permis de dégager 3 cas d'utilisation chez Mégalis / GéoBretagne : 

**1. Je suis derrière un security proxy et je suis connecté**

Je ne vois que les cartes de mon organisme. Je ne peux pas rechercher par organisation car je ne vois que les cartes de mon organisation et les cartes des utilisateurs de mon organisation.
Je ne peux éditer ou supprimer que mes propres cartes.

**2. Je suis derrière un security proxy et je ne suis pas connecté (ANONYMOUS)**

Je vois toutes les cartes de l'utilisateur ANONYMOUS et non ANONYMOUS. Je peux rechercher par organisation et retrouver toutes les cartes même des autres utilisateurs non ANONYMOUS.
Je ne peux cependant pas SUPPRIMER ou EDITER une carte d'un utilisateur connecté.
Je ne peux supprimer ou éditer que les cartes de l'utilisateur ANONYMOUS.

**3. Je suis dans une petite structure, je n'ai pas de security-proxy, j'ai un studio dit "ouvert"**

Je vois toutes les cartes.
Je n'ai pas de gestion pas utilisateur ni par organisme.
Je ne peux pas rechercher par organisation.
Je peux supprimer ou éditer toutes les cartes.
Ce fonctionnement est identique au fonctionnement non connecté (ANONYMOUS) derrière un security proxy, mais il n'y aura que des cartes ANONYMOUS.

**Comment by Gaetanbrl** [comment]
Proposition de @spelhate :

**Utiliser un nom d'organisme par défaut (e.g GéoBretagne) pour les cas 2 et 3.**

**Comment by spelhate** [comment]
Je pense qu'on peut encore simplifier.

### 1) Je suis connecté
- Je suis **"identifié"**  avec mon nom d'utilisateur et mon organisme de rattachement
- Je peux **voir** toutes les applications de mon **organisation**
- je peux éditer, publier ou supprimer mes propres cartes

### 2) je ne suis pas connecté
 - je suis **"identifié"** comme utilisateur **anonymous** de l'organisation fake "**public**"
 - Je peux voir, éditer, publier ou supprimer toutes les cartes  de l'utilisateur **anonymous** appartenant à l'organisation fake **public**

Qu'en pensez-vous ? @lecault @Gaetanbrl @Agath21 @pierrejego

**Comment by Gaetanbrl** [comment]
Merci  @spelhate ca me semble clair

**Comment by Gaetanbrl** [comment]
### A rajouter dans la doc et pour les tests

Configuration à rajouter en variable d'env ou dans settings.py pour avoir l'org "fake" : 

`DEFAULT_ORG = os.getenv("DEFAULT_ORG", "public")`

Pour la prod avec gunicorn, rajouter la variable dans `/etc/systemd/system/mviewerstudio.service `: 

`Environment="DEFAULT_ORG='public'"`


### Attention

Sur gis.jdev, le répertoire mviewerstudio et les scripts python sont dans : 

`mviewer:mviewer /home/mviewer/mviewerstudio`

C'est le user `mviewer` qui est utilisé donc.

Sauf que les répertoires de publication et de sauvegarde (public / store) sont dans :

```
www-data:www-data /var/www/mviewer/apps/store
www-data:www-data /var/www/mviewer/apps/public
```

En l'état gunicorn me renvoi : 

```
mars 17 12:05:26 vps692344 gunicorn[1936441]:   File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
mars 17 12:05:26 vps692344 gunicorn[1936441]:     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
mars 17 12:05:26 vps692344 gunicorn[1936441]: PermissionError: [Errno 13] Permission denied: '/var/www/mviewer/apps/public/e5ae51bc25b9.xml'
mars 17 12:05:26 vps692344 gunicorn[1936441]: WARNING:mviewerstudio_backend.error_handlers:An error occured. Error code 500, name: Internal Server Error
```

Pour corriger ce problème : 

1. Vérifier que mviewer doit être dans le groupe www-data
2. Changer les droits de /public et /store pour avoir :

```
mviewer:www-data /var/www/mviewer/apps/store
mviewer:www-data /var/www/mviewer/apps/public
```

Cette solution n'est potentiellement pas la meilleure et ce problème intervient car j'ai utilisé un user mviewer dans un répertoire `/home/mviewer` (à déconseiller !).

Il faudrait plutôt mettre le studio dans un répertoire qui n'est pas `/home/mviewer` dans mon cas et utiliser les droits de `www-data` et non `mviewer`.

> je ne sais pas si je suis clair, à revoir avec @pierrejego .

**Comment by lecault** [comment]
- [ ] Depuis la page Ouvrir un projet existant, les filtres ne fonctionnent pas. 
- [ ] Depuis la page Ouvrir un projet existant bouton Supprimer  : ajout d'un message de confirmation
- [ ] Depuis la page Ouvrir un projet existant avoir le nom de l'auteur (Loïc Ecault) au lieu du login (lecault)
- [ ] Pb URL avec accent exemple : https://gis.jdev.fr/mviewer/?config=apps/store/d42c3eb3f864/Lycées.xml => règles pour remplacer les caractères spéciaux
- [ ] Depuis la page publication, Remplacer prévisualiser votre application par afficher votre application avec l'url stable exemple https://gis.jdev.fr/mviewer/?config=apps/store/8f57e771b40f/ENS.xml. En commentaire : Afficher votre application dans l'état courant
- [ ] Depuis la page Historique des modifications, renommer Marquer cet état par Marquer cette version
- [ ] Après le marquage, je m'attends à revenir sur la page de l'historique des versions
- [ ] Remplacer voir les versions par voir les versions marquées. On ne voit que les version marquées. (N.B : on ne comprend pas le fonctionnement actuel du tag vert)
- [ ] Manque les tooltip sur les actions
- [ ] Si le titre a été changé, on ne peut pas restaurer une version avec le titre précédent (conserver l'ancien XML)

**Comment by Gaetanbrl** [comment]
> Si le titre a été changé, on ne peut pas restaurer une version avec le titre précédent (conserver l'ancien XML)

@lecault peux-tu décrire ce que tu as testé ici stp ? Nous ne comprenons pas ton test, cela nous aidera.

**Comment by Gaetanbrl** [comment]
je viens de tester et je vois en effet qu'il se mélange les pinceaux à certains moment. Je regarde

**Comment by Agath21** [comment]
> Depuis la page Ouvrir un projet existant, les filtres ne fonctionnent pas.
> @Gaetanbrl dit : filtre Auteur à corriger. Pour la saisie libre, il faut faire utiliser la touche "entrer" ou cliquer en dehors de l'input pour déclencher l'application du filtre. Ce comportement est relativement basique et standard.
> @Gaetanbrl dit : corrigé le 28/03/2023

Bug à résoudre : La page est rechargée lors de la validation
