### ISSUE TITLE
MEG - Finaliser la fonction d’import de thématiques Mviewer existantes

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#159]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Histoire

**En tant que** utilisateur,
**Je souhaite** pouvoir visualiser et filtrer et importer des thématiques,
**Pour** afin d’améliorer la fenêtre d’import de thématiques existantes

## Description complémentaire

Le principe de cette fonctionnalité est de proposer à l’utilisateur des **thématiques** d’applications mviewer « prêtes à l’emploi ». Les thématiques sont des thématiques d’application mviewer publiées sur le Web et listées dans un fichier de type csv. Une amorce d’implémentation existe déjà dans mviewer studio à partir de l’inventaire suivant : https://geobretagne.fr/minicatalog/csv
![image](https://user-images.githubusercontent.com/1793792/216944604-e8837f9d-6d1c-4dd6-9aaf-ebf8d1336463.png)

La source de donnée associée se trouve ici : https://lite.framacalc.org/codesprintbegmeil

L’import de thématiques fonctionne actuellement avec tous les types de couches y compris les **customlayers** dès lors que toutes les URL des ressources nécessaires sont précisées en **absolu et servies avec les entêtes CORS**.

Il est nécessaire de **revoir l’écran** permettant de sélectionner la /les thématiques avec les ajouts suivants afin de faciliter l'exploration du catalogue de thèmes et la compréhension de chaque thème :

- Filtrage des thématiques par nom ou mot clé, producteur, statut (observations = ‘Ok’) ;
- Affichage de la description, du logo, observations de la source (Ok, pas à jour...) ;
- Bouton sélectionner plus accessible ;
- Créer une option d’affichage pour :
    - afficher toutes les couches de la thématique au démarrage ;
    - aucune couche au démarrage ;
    - affichage des couches par tel que défini dans le XML source.

**Comment by Agath21** [comment]
## Proposition d'interface et parcours utilisateur

Dans le module "Thématiques & Données", je clique sur "Importer", un nouvelle modale s'ouvre avec les thématiques externes :
 
![Studio2_importExternThem](https://user-images.githubusercontent.com/22764056/226868703-848af1df-6f6e-4b49-af22-929838b9fa40.png)

Pour chaque thématique, je visualise : 
- Le nom
- La description 
- Le statut
- Le créateur 

J'ai la possibilité de les filtrer via une barre de recherche en haut à droite. 

Pour améliorer la visibilité, nous proposons d'ajouter un système de pagination.

**Comment by spelhate** [comment]
Ok de mon côté également.

**Comment by Agath21** [comment]
Développement à réaliser : 

- [ ] Mettre à jour l'interface en affichant le nom, la description, l'organisme
- [ ] Barre de recherche pour filtrer les thématiques 
- [ ] Pagination et gestion de l'affichage 
- [ ] Filtrer les thématiques et n'afficher que celle avec le statut "à jour"

**Comment by Agath21** [comment]
> Créer un nouveau paramètre pour la gestion de l'affichage des couches au sein de la thématique

Pour gérer l'affichage des couches au sein d'une thématique externe lors du démarrage de l'application, création d'un nouveau paramètre `layersvisibility` spécifique aux thématiques externes avec les valeurs possibles : 

- `default` : Afficher les données par défaut comme défini dans l'application source
- `all` : Afficher toutes les données de la thématique externe
- `none` : Aucune donnée n'est affichée

Exemple : 

```
<theme id="education" url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml" name="Education et formation" collapsed="true" icon="false" layersvisibility="none"> 
</theme>
```

**Comment by Gaetanbrl** [comment]
> création d'un nouveau paramètre layersvisibility spécifique aux thématiques externes avec les valeurs possibles

@lecault @spelhate est-ce que ce nouveau paramètre studio vous convient ?

**Comment by lecault** [comment]
ça correspond au besoin oui merci.

**Comment by spelhate** [comment]
Ok pour moi. Issue mise à jour côté mviewer : https://github.com/mviewer/mviewer/issues/616

**Comment by lecault** [comment]
Dans cette issue, il y avait aussi la possibilité de modifier le nom de la thématique (le name).
Le dev est côté mviewer, côté studio, prévoir de modifier le nom de la thématique.

**Comment by lecault** [comment]
Suite à test sur la branche-159

- [ ] Rendre la modification possible du name de la thématique via IHM (modif à faire côté mviewer https://github.com/mviewer/mviewer/issues/616)

On n'a pas pu testé l'import dans mviewer à cause problème de proxy

**Comment by Gaetanbrl** [comment]
> On n'a pas pu testé l'import dans mviewer à cause problème de proxy

Le problème n'est pas réglé avec la whitelist du proxy backend studio ?

**Comment by Gaetanbrl** [comment]
> Rendre la modification possible du name de la thématique via IHM (modif à faire côté mviewer https://github.com/mviewer/mviewer/issues/616)

c'est pas en lien avec https://github.com/mviewer/mviewerstudio/issues/180 @lecault ?

**Comment by spelhate** [comment]
> Ok pour moi. Issue mise à jour côté mviewer : [mviewer/mviewer#616](https://github.com/mviewer/mviewer/issues/616)

PR mviewer réalisée ce jour : https://github.com/mviewer/mviewer/pull/753

**Comment by Gaetanbrl** [comment]
> Lorsqu'on importe une thématique dans le XML studio renseigne toujours les valeurs suivantes pour les paramètres collapsed et icon :
collapsed="true" icon="false"

Ca donne quoi en v3.2 (latest) @lecault ?

**Comment by Gaetanbrl** [comment]
ok du coup c'est une issue hors MEG => A traiter si on a le temps dans le cadre des travaux MEG donc.

**Comment by lecault** [comment]
J'ai fait une issue spécifique #196

**Comment by Gaetanbrl** [comment]
@lecault @spelhate avez-vous pu tester ?

Pour rappel le proxy est utile sur notre instance pour utiliser vos flux avec le studio (voir ici [également](https://github.com/mviewer/mviewerstudio/issues/186#issuecomment-1534142023))

* proxy activé 

On peut appeler les flux de la région.
On ne peut pas utiliser les thématiques externes car mviewer utiliser la valeur du proxy.

* proxy désactivé

On ne peut pas utiliser les flux région (erreur CORS).
Mais on peut utiliser les thématiques externens.

**Comment by Agath21** [comment]
Pour information, nous avons désactivés le proxy sur https://gis.jdev.fr/ pour que vous puissiez tester l'import des thématiques externes et la gestion de l'affichage des couches.

**Comment by spelhate** [comment]
Pas pu tester sur  https://gis.jdev.fr/mviewerstudio/ . j'ai une fenêtre vide lorsque je souhaite importer une thématique : 
![image](https://github.com/mviewer/mviewerstudio/assets/1793792/228317a8-9f56-4236-bbfd-dc0886f55b77)

**Comment by Gaetanbrl** [comment]
Etrange on ne reproduis pas @Agath21 et moi :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/9a4b1fc3-f489-4197-b65c-8568ae4e5f44)

**Comment by lecault** [comment]
Je vois les thématiques aussi

**Comment by spelhate** [comment]
Oui ça marche maintenant chez moi également.

**Comment by Gaetanbrl** [comment]
A fermer @spelhate @lecault ?

**Comment by spelhate** [comment]
Ok.
