### ISSUE TITLE
MEG - Intégration d’un « générateur / assistant » de templates

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#160]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Histoire

**En tant que** utilisateur,
**Je souhaite** utiliser une interface simple et intuitive de génération des templates (fiche info)
**Pour** reprendre ou réaliser facilement des templates Mustache pour chacune des couches de mon application

## Description complémentaire

Exemple avec la version 3.1, il est possible de générer un template Mustache en cochant l'option "Utiliser un template"
![image](https://user-images.githubusercontent.com/1793792/216956677-dbf84c42-d7d8-43d9-9f4b-1a4e2d33bf50.png)
Ce qui produit une template intégré dans le config.xml : 

```xml
<template>
    <![CDATA[
        {{#features}} 
             <li class="item" style="width:238px;"> 
                 <h3 class="title-feature">{{nom}}</h3> 
                 <p class="text-feature"></p> 
                 <img src="{{photo}}" class="img-responsive" style="margin-top:5%;" /> 
              </li> 
        {{/features}}]]>
</template>

```

En s’appuyant sur l’existant, il faut revoir la génération de templates pour :

- Choisir un modèle de template (en s’appuyant si possible sur les patrons de templates déjà créés : https://github.com/geobretagne/mviewerstudio/issues/100)
- Réadapter les templates pour un affichage « responsive » sur mobile ou tablette
- Modifier les éléments et leur disposition (ex : affichage de type texte devient affichage de type hyperlien)
- Visualiser le rendu
- Ajouter un nouvel affichage de type iframe avec paramétrage du pattern de l’URL (ex : https ://monsite.com/{{mon_champ}})
- Ajouter des conditions d’affichage si non nul par exemple
- Enregistrer le template dans un fichier plutôt que dans le contenu du nœud `<template>`

RAF au 15/05/2023 : 

- [x] Doc utilisateur (rebase branche userdoc-198)
- [x] Interface proposée par @Agath21
- [x] Rebase entre branches : develop-meg -> issue-160
- [x] Gestion entre URL Externe / template créé par le générateur / template par défaut 
- [x] test avec backend PHP
- [x] Correction de la prévisualisation (+ adaptation URL)
- [x] Syntax conditionnelle pour les type `field` uniquement (vu cotech du 16/05)
- [ ] tests utilisateurs

**Comment by spelhate** [comment]
En complément de ce qui est décrit plus haut je décris le parcours utilisateur souhaité.

1. je souhaite mettre en forme la fiche d'information d'une couche
2. Pour cela je créée un template qui s'applique à ma couche à partir d'un modèle que je choisis via l'IHM
3. L'**assistant Template** me propose alors les champs disponibles de la couche et les "affichages" possibles pour chaque champ : ( Titre, texte, lien hyper texte, image, iframe ) 
4. Pour chaque champ utilisé dans le template, je peux lui affecter un alias qui remplacera le nom du champ dans la fiche d'information.
5. En mode avancé, l'IHM affiche le code source du template. Ce code source de template est modifiable à la main par l'utilisateur, avec affichage du rendu en live.
6. L'enregistrement définitif du template se fait au moment de l'enregistrement de l'application. L'enregistrement consiste en un fichier **mst** créé sur le serveur dans le dossier de l'application versionnée.

**Comment by Gaetanbrl** [comment]
> En mode avancé, l'IHM affiche le code source du template. Ce code source de template est modifiable à la main par l'utilisateur, avec affichage du rendu en live.

@spelhate tu détails dans l'étape 5 du WYSIWYG ?

**Comment by spelhate** [comment]
> 

Non. Juste donner la possibilité à l'utilisateur de modifier quelques éléments à la main. Exemple Passée d'un h1 à un h3, mettre des sauts de ligne...

**Comment by Gaetanbrl** [comment]
Mais via un éditeur intégré qui prend le code à chaud c'est ca ?

**Comment by lecault** [comment]
Avec un peu de retard, voici mes commentaires  : 
Pour le point 3 est ce qu'il faut décrire tous les cas possibles ?
J'ajouterai sous-titre, description (police plus fine italique) et le lien doit apparaître sous la forme d'un bouton (avec le nom de l'alias). Un plus serait l'ajout possible de texte libre.
Pour le point 4 : ajout pour chaque champ utilisé d'une option permettant de masquer le champ si pas de valeur ({{#secteurs}} {{/secteurs}}) et de la possibilité de mettre plusieurs champ dans un alias. Exemple pour une adresse : (<b>Adresse :</b> {{adresse}} {{code_postal}} {{ville}})
Le point 5 sera apprécié avec le rendu en live. 
Pour le point 6: nom du mst = nom de l'id de la couche

**Comment by Gaetanbrl** [comment]
> Est ce qu'il faut décrire tous les cas possibles ?

On va garder le fonctionnement classique.

Tous les cas spécifiés et prévus dans le CCTP seront couverts. Plus c'est précis, moins il y a d'erreurs ou de surprises possibles.
C'est pour cela qu'on a besoin d'un maximum de détails à part de votre besoin (besoin = élément connu dans le  CCTP qu'on a su estimer).

**Comment by Agath21** [comment]
# Proposition d'interface et parcours utilisateur

## Scénario 1 | Basé sur des modèles

Après avoir sélectionner une donnée (ici `Lycées de Bretagne`), l'utilisateur ouvre les options de la couche. Il se positionne dans l'onglet Interrogation et seléctionne `Personnalisée` pour le _Format de la fiche d'information_ : 

1 . L'utilisateur crée un nouveau template dans le bloc _Configurer la fiche d'information_ en cliquant sur le bouton `Créer`
![MS_userCase_templateGenerator_S1_1](https://user-images.githubusercontent.com/22764056/231188567-15299fab-d829-44d9-ac34-6219f3323821.png)

2 . Une nouvelle fenêtre s'ouvre indiquant la donnée concernée et la position de la fiche précédemment sélectionnée. L'utilisateur sélectionne un template parmi les modèles prédéfinis dans la liste 
![MS_userCase_templateGenerator_S1_2](https://user-images.githubusercontent.com/22764056/231188907-25397047-0037-40cc-b066-9083c7e36719.png)

3 . La structure du template s'affiche avec les différents composants. L'utilisateur indique pour chaque composant les valeurs à utiliser : 
![MS_userCase_templateGenerator_S1_3](https://user-images.githubusercontent.com/22764056/231189594-cde8f38b-111e-4136-9217-fa65a4ef162a.png)

Trois types de champs sont possibles : 
- Champ dynamique (données)
- Champ statique (saisie par l'utilisateur en brut)
- Concaténation de champs dynamiques

4 . L'utilisateur peut prévisualiser son template en cliquant sur le bouton `Prévisualiser` : 
![MS_userCase_templateGenerator_S1_4](https://user-images.githubusercontent.com/22764056/231189761-8601037f-ab27-4e88-9a5d-650d407658f0.png)

5 . Après avoir cliqué sur Enregistrer, l'utilisateur peut éditer ou supprimer son template généré à l'image du système des couches : 
![MS_userCase_templateGenerator_S1_5](https://user-images.githubusercontent.com/22764056/231190092-6d7e28d8-c033-42b8-a34d-c7c373bb0ffb.png)

## Scénario 2 | Structure libre

Après avoir sélectionner une donnée (ici `Lycées de Bretagne`), l'utilisateur ouvre les options de la couche. Il se positionne dans l'onglet Interrogation et seléctionne `Personnalisée` pour le _Format de la fiche d'information_ : 

1 . L'utilisateur crée un nouveau template dans le bloc _Configurer la fiche d'information_ en cliquant sur le bouton `Créer`
![MS_userCase_templateGenerator_S1_1](https://user-images.githubusercontent.com/22764056/231188567-15299fab-d829-44d9-ac34-6219f3323821.png)

2 . Une nouvelle fenêtre s'ouvre indiquant la donnée concernée et la position de la fiche précédemment sélectionnée. La structure du template est vide, l'utilisateur clique sur le bouton `Ajouter un composant` :
![MS_userCase_templateGenerator_S2_1](https://user-images.githubusercontent.com/22764056/231190757-78b05d22-7c54-47a0-865d-87962a5cb14d.png)

3 . Une librairie de composants prédéfinis s'ouvre, l'utilisateur sélectionne le composant qu'il souhaite ajouter : 
![MS_userCase_templateGenerator_S2_2](https://user-images.githubusercontent.com/22764056/231191140-2ced63e6-fa9f-419b-ba50-bdc0f98dda10.png)

4 . L'utilisateur configure ensuite les paramètres du composant : 
![MS_userCase_templateGenerator_S2_3](https://user-images.githubusercontent.com/22764056/231191372-a6ca8960-0e4b-4dc2-a914-b11feb4c5e99.png)

Il peut : 
- ajouter un composant supplémentaire
- supprimer un composant 
- modifier la position d'un composant (drag & drop)

5 . Il prévisualise son template comme dans le scénario 1 en cliquant sur `Prévisualiser` : 
![MS_userCase_templateGenerator_S2_4](https://user-images.githubusercontent.com/22764056/231191716-669fe76b-addf-41ba-882a-d57a298e5c3d.png)

## Avantages & inconvénients

|               | Scénario 1                                                                     | Scénario 2                                                             |
|---------------|--------------------------------------------------------------------------------|------------------------------------------------------------------------|
| Avantages     | Modèles prédéfinis -> Utilisation facilité                                     | Système libre et modulaire \| Evolution de la librairie des composants |
| Inconvénients | Peu de souplesse dans la composition des fiches \| Utilisation plus restreinte | Page blanche                                                           |

**Comment by Agath21** [comment]
## Librairie des composants 

Liste des composants disponibles avec les paramètres à indiquer pour l'utilisateur : 

| Composant   | Paramètre(s)       | dynamique | statique | concat. |
|-------------|--------------------|-----------|----------|---------|
| Titre       | texte              | x         | x        | x       |
| Sous-titre  | texte              | x         | x        |         |
| Image       | url                | x         | x        |         |
| Bouton      | intitulé \| url    | x         | x        |         |
| Texte       | texte              | x         | x        | x       |
| Chiffre clé | valeur \| intitulé | x         | x        |         |
| Iframe      | url                | x         | x        |         |
| Liste       | texte              | x         | x        |         |

**Comment by Gaetanbrl** [comment]
Modèles de template pour le panneau de droite et du bas par @Agath21 qui servent de base pour la réalisation des composants du scénario 2 validé par @spelhate @lecault : 

[templates mdels.zip](https://github.com/mviewer/mviewerstudio/files/11229476/templates.mdels.zip)

**Comment by Gaetanbrl** [comment]
Travaux démarrés dans la branche : 

https://github.com/jdev-org/mviewerstudio/tree/issue-160

**Comment by Gaetanbrl** [comment]
Apperçu des travaux en cours sur la branche jdev-org/issue-160 : 

![chat_studio_template](https://user-images.githubusercontent.com/16317988/235159894-7f07ff5a-1579-400f-a069-b9dce972cfee.gif)

**Comment by lecault** [comment]
Super merci pour la première démo.
Il manque juste le type de composant texte. D'ailleurs celui-ci est utilisé nativement de la forme : Ville : Rennes
Dans le système proposé on utiliserait donc l'option "à partir de plusieurs champs".

Du coup l'intitulé "à partir de plusieurs champs" n'est pas très clair. J'opterai pour "formule personnalisée" à valider avec @spelhate 

Concernant le type "à partir de plusieurs champs", on peut quand même ajouter plusieurs champs et plusieurs valeurs statiques ?
Enfin, je trouverai bien qu'on différencie graphiquement un champ et une valeur statique par exemple par la couleur (valeur statique en blanc, champ en coloré).

**Comment by Gaetanbrl** [comment]
> Il manque juste le type de composant texte

En effet.

> Concernant le type "à partir de plusieurs champs", on peut quand même ajouter plusieurs champs et plusieurs valeurs statiques ?

>  je trouverai bien qu'on différencie graphiquement un champ et une valeur statique

oui, c'est une option de la lib qui permet d'ajouter des valeurs dans la liste, je trouvais ca intéressant et ce n'est pas obligatoire. 

Dans tous les cas, je ne ferai pas d'évolution sur ce point étant donné qu'une modification graphique serait une surcharge de la librairie. Sinon n'ayant pas de temps pour ce type d'évolution, j'enlèverai la possibilité de faire de la concaténation de champs + valeurs statique via ces tags, il faudra alors utiliser la syntaxe du champ "valeur statique".

**Comment by Gaetanbrl** [comment]
Questions (pour cotech ?) / contraintes relevées : 

1. Lorsqu'on prévisualise, on a besoin d'avoir accès à une donnée (entité) pour disposer des attributs à previsualiser. Depuis un WMS, comment procéder (e.g via un getFeatureInfo) ? Avec quel parcours utilisateur ?

2. Lorsqu'on prévisualiser, nous n'avons pas souhaité ajouté de CSS dans le template de chaque composant (e.g Titre) car nous souhaitons que lorsque le template est chargé dans le mviewer de destination, ce soit le CSS du mviewer qui soit utilisé. Le chargement préalable du CSS d'un mviewer dans studio risquerait de parasiter le CSS natif du studio. Aucune solution technique reste à trouver pour avoir une zone de prévisualisation "esthétique".
