### ISSUE TITLE
MEG - Fluidifier le workflow de création/publication d’applications Mviewer sur GeoBretagne

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#161]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Histoire

**En tant que** utilisateur du mviewerstudio sur la plateforme GeoBretagne,
**Je souhaite** pouvoir disposer d'une interface simple
**Pour**  pouvoir déployer facilement une application en développement (beta) sur l'environnement de production

## Description complémentaire

(à compléter si nécessaire)

**Comment by Agath21** [comment]
## Proposition d'interface et parcours utilisateur

### CAS 1 : Création d’une nouvelle application + passage en production
1 – Lors de la création d’une nouvelle application, le statut « Brouillon » est le statut par défaut. Il est indiqué par un badge dans le bloc « Wizard » à côté du titre : 
![01](https://user-images.githubusercontent.com/22764056/223471117-47bc8d30-84f7-4733-84ec-794f598d7d7c.png)

2 – Je réalise la configuration de ma nouvelle application 

3 – Dans le module « Publication », je clique sur « Publier votre application » :
![usercase02](https://user-images.githubusercontent.com/22764056/223471205-a1305935-e7e3-43e3-8c6b-5b7e469bc23b.png)

4 – Une nouvelle fenêtre s’ouvre indiquant que l’application est disponible en ligne avec un lien de partage et un lien pour intégrer sa carte en iframe.
![usercase03](https://user-images.githubusercontent.com/22764056/223471238-674581da-02c2-4c12-9bb4-0374c94d37df.png)

**NOTE :** 

- Tant que l’utilisateur n’aura pas publié son config.xml, l’application restera en statut « brouillon » 
- Le parcours utilisateur est identique pour passer une application existante « brouillon » en mode « en ligne  »

### CAS 2 : Gestion d’une application publiée 

1 – Au sein de la page d’accueil, j’ouvre un projet existant en cliquant sur « Ouvrir un projet » et je sélectionne mon application : 
![usercase04](https://user-images.githubusercontent.com/22764056/223472350-8bf09108-3006-4d19-96ac-5b755df58712.png)
_Le statut de l’application est « en ligne », l’application a donc été publiée auparavant._ 

**Modification d’une application en ligne**

3 – Je réalise mes modifications. 

4 – Pour publier mes modifications sur l’application en ligne, je dois cliquer sur publier les modifications :
![usercase06](https://user-images.githubusercontent.com/22764056/223476063-244131eb-b736-43b0-88b8-fd62dcd19c76.png)

## Mécanique
![image](https://user-images.githubusercontent.com/22764056/223486059-e756ce93-c3e6-4347-8626-a4d47549b655.png)

 - On crée et modifie mon_application.xml dans le studio avec le statut "brouillon"
 - Quand on publie une application, on copie le xml à l'instant T dans prod/ (voir écran ci-dessus CAS 1)
 - Dès publication d'une app, on ajoute un paramètre dans le XML indiquant que l'app est publiée 
 - L'application passe alors sous le statut "en ligne"
 - Les modifications sont ensuite réalisée dans le studio et et exclusivement dans le dossier beta/ avec le statut "En ligne" (capté à l'aide du nouveau paramètre) (voir écran ci-dessus CAS 2)
 - Ces modifications ne sont donc pas automatiquement publiées, il est nécessaire d'appuyer sur "publier mes modifications" pour réaliser une nouveau copier/coller dans prod/mon_application.xml. 
 - On peut donc réaliser une évolution de son app à différent moment sans perturber l'application en prod et utiliser la gestion des versions.

### Questions : 
- Peut-on dépublier une application ? et donc passer de "en ligne" à "brouillon"

**Comment by Agath21** [comment]
> Peut-on dépublier une application ? et donc passer de "en ligne" à "brouillon"

Ok pour ajouter un bouton "dépublier"

## Proposition d'interface : 
Accès en mode avancée > "Options" > "Dépublier une application"

![usercase07](https://user-images.githubusercontent.com/22764056/223668508-ec494ad8-7dc5-4de1-8423-f13170262227.png)

**Comment by Gaetanbrl** [comment]
### Validé dans le point du 08/03/2023

 - On crée et modifie `mon_application.xml` dans le studio avec le statut "brouillon"
 - Quand on publie une application, on copie le xml à l'instant T dans `prod/` (voir écran ci-dessus CAS 1)
 - Dès publication d'une app, on ajoute une information dans une balise dédiée dans le XML qui indique que l'app est publiée
 - L'application passe alors sous le statut "en ligne"
 - Les modifications sont ensuite réalisée dans le studio et et exclusivement dans le dossier `beta/` avec le statut "En ligne" (capté à l'aide du nouveau paramètre) (voir écran ci-dessus CAS 2)
 - Ces modifications ne sont donc pas automatiquement publiées, il est nécessaire d'appuyer sur "publier mes modifications" pour réaliser une nouveau copier/coller dans `prod/mon_application.xml`. 
 - On peut donc réaliser une évolution de son app à différent moment sans perturber l'application en prod et utiliser la gestion des versions.
 - Le bouton `"ouvrir dans studio"` n'est visible que pour les applications créent via mviewerstudio
 - Lors du clic sur le bouton "ouvrir dans studio", il est prévu d'ouvrir mviewerstudio sur la version du XML telle qu'elle est disponible avec ses dernières modifications dans le répertoire `beta/` et non sur l'état du XML visible dans le répertoire `/production`
 - Depuis studio, il est possible d'ajouter un bouton "dépublier" pour une application qui est disponible dans le répertoire `/prod`

**Comment by Gaetanbrl** [comment]
### A rajouter dans la doc et pour les tests

Configuration à rajouter en variable d'env ou dans settings.py pour avoir l'org "fake" : 

`DEFAULT_ORG = os.getenv("DEFAULT_ORG", "public")`


Pour la prod avec gunicron, rajouter la variable dans `/etc/systemd/system/mviewerstudio.service `: 


`Environment="DEFAULT_ORG='public'"`

**Comment by Gaetanbrl** [comment]
Les spécifications supplémentaires et détaillées étant survenus il y a 2 jours (voir dernier commentaire de @spelhate), le code actuel commencé bien avant ne prévoit pas l'organisation par répertoire pour les éléments publiés mais juste une dépose du XML dans un répertoire de publication. Cette logique se basée sur les derniers échanges et les maquettes / schéma échangés plus haut en COTECH et dans cette issue.

Ces nouvelles spécifications seront donc prises en compte à mon retour le 27/03/2023.

**Comment by lecault** [comment]
Scénario proposé :
- Après clic sur publication, on arrive sur une modale qui propose un mon_unique_app par défaut que l'utilisateur peut modifier (pas de caractères spéciaux, ni d'espaces).
- Clic sur Publier publie l'application et renvoie sur la page actuelle avec les liens de partage
- Dans cette page, le bouton retour renvoi à la page de saisie de mon_unique_app

Règles du mon_unique_app par defaut : les mêmes que pour le XML à savoir : 
- Remplacer les espaces par underscores
- Mettre tout en minuscule
- Remplacer les accents par les lettres sans accents (idem pour ç)
- Remplacer les autres caractères spéciaux (&, %) par un undescore
- Limiter à 20 caractères

**Comment by Gaetanbrl** [comment]
@lecault @spelhate, après réflexion, est-ce qu'il ne serait pas aussi intéressant de pouvoir saisir un nom unique dès la création de l'application et non pas lors de la publication ?

Le parcours utilisateurs serait donc le suivant : 

1. Clic sur "Créer"
2. Modifier la configuration
3. Saisir un nom unique qui ne sera pas basé sur le titre dans un input ou dans une modal lors du 1er clic sur "Enregistrer"
4. Cliquer sur "Publier" => Fonctionnement actuel, pas de changement de nom possible

Avec des noms homogène entre le mode brouillon et publié, ce parcours permet de faciliter l'identification d'une application entre le répertoire brouillon et le répertoire publication car le nom est commun.
Sinon, il faut un mapping (complexité +) pour savoir quel brouillon correspond à quel application publiée étant donné que le nom est différent.

Depuis l'IHM d'édition, cela permet en autre de télécharger l'application avec un nom "final" qui est également le nom de l'application publiée.

Le téléchargement impose également de prévoir une mécanique de création de ZIP dans le backend afin de récupérer un XML et l'ensemble de ses ressources (customX, mst...). Ce point n'avait pas été soulevé jusque là.

**Comment by Gaetanbrl** [comment]
> Sinon, il faut un mapping (complexité +) pour savoir quel brouillon correspond à quelle application publiée étant donné que le nom est différent.

Pour ce point, je vois sinon que DublinCore permet d'ajouter une relation.

On peut alors faire un mapping facilement sans avoir de code complexe dans le XML directement via une balise `Relation` : 

https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/relation/

Ainsi, lors de la suppression d'un XML ou de sa re publication, nous pourrons lire la meta Relation et identifier facilement le bon XML dans le répertoire de publication.

**Comment by lecault** [comment]
Quand tu dis nom on est bien d'accord qu'on parle du nom du dossier. Je trouve l'idée intéressante de saisir ce nom au premier enregistrement. Il faut que studio propose un nom par défaut
Question : est ce que le dossier physique de stockage de brouillon porte le même nom ? Si oui, on pourrait avoir des soucis car ce dossier contient toutes les apps de tous les partenaires (contrairement à la publication en prod par organisme).

Par contre, le fait de ne pas pouvoir le modifier est un soucis : on ne sait pas toujours la finalité de l'app à la création. A minima au passage en production. Donc on échappera pas à un mapping.

**Comment by lecault** [comment]
> Je ne suis pas certain de comprendre. A quel dossier fais-tu référence ?

Au dossier dans store : https://gis.jdev.fr/mviewer/?config=apps/store/383b7e1e9136/VN.xml
Mais la présence de dossier par organisme résous le truc (il me semblait bien qu'il y avait ça pour le mode brouillon mais je ne savais plus où.
Et oui on est d'accord là dessus.

> * [ ]  Après clic sur publication, on arrive sur une modale qui propose un mon_unique_app par défaut que l'utilisateur peut modifier (pas de caractères spéciaux, ni d'espaces).

C'est ici que je faisais référence au nom par défaut. Et oui à partir du titre en corrigeant les caractères spéciaux.
Quelques exemples de titre avec leur correspondance en nom d'appli : 
Voies navigables => voies_navigables
Filière de maçonnerie => filiere_de_maconnerie
Appli 100% => appli_100

**Comment by spelhate** [comment]
> Le téléchargement impose également de prévoir une mécanique de création de ZIP dans le backend afin de récupérer un XML et l'ensemble de ses ressources (customX, mst...). Ce point n'avait pas été soulevé jusque là.
👍 +1

**Comment by spelhate** [comment]
> Merci Loïc, je vais donc garder ce fonctionnement conformément au CR du COTECH :
> 
>     * 1 organisme = 1 répertoire que ce soit en brouillon ou en publication
> 
>     * 1 nom = nom du répertoire des ressources du XML
> 
>     * 1 nom = nom du XML (identique au nom du répertoire des ressources)
> 
>     * Demande de personnalisation du nom à la publication ==> Utilisation de la balise `<dc:relation>` pour lier le brouillon et la publication
> 
>     * Lors de la publication (clic sur "Publication") :
>       Par défaut on propose titre normalisé ([voir règles](https://github.com/mviewer/mviewerstudio/issues/161#issuecomment-1483047482))
>       L'utilisateur peut alors modifier le nom.
> 
> 
> Ce nom sera réutilisé tel que pour un nom "Voies navigables" on obtiendra dans le répertoire de publication (et uniquement dans celui-ci) un XML `voies_navigables.xml` et un répertoire `organisme/voies_navigables` au même niveau que le XML dans le répertoire de l'organisme d'appartenance.
> 
> > _Je verrai ensuite selon le temps, si l'utilisateur peut adapter le nom dès la création._

Ok pour moi

**Comment by lecault** [comment]
> Merci Loïc, je vais donc garder ce fonctionnement conformément au CR du COTECH :
> 
> * 1 organisme = 1 répertoire que ce soit en brouillon ou en publication
> * 1 nom = nom du répertoire des ressources du XML
> * 1 nom = nom du XML (identique au nom du répertoire des ressources)
> * Demande de personnalisation du nom à la publication ==> Utilisation de la balise `<dc:relation>` pour lier le brouillon et la publication
> * Lors de la publication (clic sur "Publication") :
>   Par défaut on propose titre normalisé ([voir règles](https://github.com/mviewer/mviewerstudio/issues/161#issuecomment-1483047482))
>   L'utilisateur peut alors modifier le nom.
> 
> Ce nom sera réutilisé tel que pour un nom "Voies navigables" on obtiendra dans le répertoire de publication (et uniquement dans celui-ci) un XML `voies_navigables.xml` et un répertoire `organisme/voies_navigables` au même niveau que le XML dans le répertoire de l'organisme d'appartenance.
> 
> > _Je verrai ensuite selon le temps, si l'utilisateur peut adapter le nom dès la création._

ok pour moi.
 
Question : si on clique sur enregistrer et que le nom existe déjà quel comportement ? On peut la renommer depuis le bouton enregistrer ?

**Comment by Gaetanbrl** [comment]
>Question : si on clique sur enregistrer et que le nom existe déjà quel comportement ? On peut la renommer depuis le bouton enregistrer ?

Voici le scénario que vous avez convenu avec @Agath21 pour ce cas :

1. Saisie du nom
2. Clic sur "Publier"
3. Alerte "Cette application existe déjà"
5.a. Souhaitez-vous l'écraser ? => supprime et remplace l'application existante
5.b Conserver et renommer l'application à publier

Est-ce que cela convient @lecault ?

**Comment by lecault** [comment]
> > Question : si on clique sur enregistrer et que le nom existe déjà quel comportement ? On peut la renommer depuis le bouton enregistrer ?
> 
> Voici le scénario que vous avez convenu avec @Agath21 pour ce cas :
> 
> 1. Saisie du nom
> 2. Clic sur "Publier"
> 3. Alerte "Cette application existe déjà"
>    4.a. Souhaitez-vous l'écraser ? => supprime et remplace l'application existante
>    4.b Conserver et renommer l'application à publier
> 
> Est-ce que cela convient @lecault ?

ok pour nous

**Comment by spelhate** [comment]
La branche 161 ne semble pas fonctionnelle : 
![image](https://user-images.githubusercontent.com/1793792/229159461-e7aa73bc-7632-4404-802d-df36435111cb.png)

**Comment by Gaetanbrl** [comment]
le `apps/config.json` est bon ? 

A tester avec : 

https://jsonformatter.curiousconcept.com/

**Comment by Gaetanbrl** [comment]
Après réflexion avec @Agath21  @spelhate @lecault il y a un cas ou écraser les données est problématique.
Le cas survient quand un utilisateur tente de publier son application avec le nom d'une application qui existe déjà, d'un autre utilisateur du même organisme.

L'existence d'un doublon ne doit pas seulement relever d'un simple contrôle sur le nom mais aussi sur les droits afin de ne pas écraser la carte d'un autre utilisateur du même groupe qui porterai le même nom dans le répertoire `/publication`.

On a donc repensé le parcours avec Agathe ce matin en pensant à 2 cas  :

* **CAS 1 - L'utilisateur souhaite publier à nouveau une carte déjà publiée mais avec un autre nom**

Nous proposons que dans tous les cas, une carte ne puisse pas être renommée via l'IHM.
Pour renommer une carte, il faut la dépublier et la publier à nouveau en utilisant le champ "nom" de l'application lors du clic sur "Publier".

* **CAS 2 - L'utilisateur souhaite publier une première fois une carte avec un nom de carte d'un autre utilisateur qui existe déjà dans le répertoire de publication pour le même organisme**

Le risque ici est d'écraser une carte qui ne nous appartient pas mais qui appartient à un utilisateur de notre organisation.

Nous proposons qu'après avoir choisi le nom de l'application, si le nom existe déjà, l'interface oblige à annuler ou bien à renommer l'application.

![image](https://user-images.githubusercontent.com/16317988/229512201-07dee710-a805-461d-8e7c-c5f4fc148267.png)

**Comment by lecault** [comment]
Ah bien vu !
Le traitement de vos 2 cas me va.

**Comment by spelhate** [comment]
> `apps/config.json`

J'ai des difficulté pour faire fonctionner la branche issue-161. le checkout  + git pull depuis develop-meg génère des conflits de merge : 
![image](https://user-images.githubusercontent.com/1793792/229790343-d428cce5-5909-41e8-8465-cf2eb8c60c88.png)

**Comment by spelhate** [comment]
Retour test branche issue-161 : en mode déconnecté, le dossier de publication est doublé : 
![image](https://user-images.githubusercontent.com/1793792/229839602-79aef757-8766-4409-9444-2a012d50249e.png)

**Comment by spelhate** [comment]
lien de partage incomplet
![image](https://user-images.githubusercontent.com/1793792/229842284-85f46be6-1310-4b94-a347-a39499a01a61.png)

**Comment by Gaetanbrl** [comment]
@spelhate je viens de t'envoyer un message via Element.
En effet, c'est l'URL complète utilisée par Python pour coller le fichier.

Pour avoir une URL accessible, il faut être certain que l'URL pointe vers un répertoire de publication dans mviewer/apps comme c'est le cas pour le mviewer/apps/store.

Pour un répertoire /public, on aurait alors donc mviewer/apps/store.

Est-ce que vous pouvez me confirmer que le répertoire de publication est bien dans le répertoire apps de mviewer pour qu'on puisse bien créé une URL accessible de l'extérieur ? @spelhate @lecault

**Comment by spelhate** [comment]
> our avoir une URL accessible, il faut être certain que l'URL pointe vers un répertoire de publication dans `mviewer/apps` comme c'est le cas pour le `mviewer/apps/store`.

Pourquoi cette contrainte ?
ça doit marcher même si le store est extérieur à mviewer. Exemple  /applications/store

**Comment by spelhate** [comment]
Je précise que je n'ai rien configuré avant de tester cette branche. Il va falloir que je commence par ça.

**Comment by Gaetanbrl** [comment]
> Il va falloir que je commence par ça.

Ah ! Je roll back ma dernière modif que j'ai rajoutée en pensant que tu voulais que ca pointe vers un repo mviewer... je dois apporter un correctif.

Sinon il faut : 

1. adapter la config (notamment config.json > mviewer_publish) 

>A noter que le nom de paramètre mviewer_publish est en train de devenir publish_folder

2. Rajouter votre règle de rewrite apache

Pour réorienter vers le bon répertoire

3. Adapter dans settings.py le répertoire de publication

Sinon la doc a été mise à jour mais dans cette branche pour cette config ;)

**Comment by spelhate** [comment]
Ok. je ferme
