### ISSUE TITLE
[MEG] - Prise en charge du type de couche TMS VECTOR

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#163]
> Issue développée dans le cadre d'une prestation JDev / Megalis Bretagne / GeoBretagne

## Besoin

Avoir la possibilité d'ajouter en tant que "baselayer" ou "layer" d'une carte Mviewer une ressource de type tuiles vectorielles - TMS/WMTS de l'IGN. cf https://github.com/mviewer/mviewer/pull/697

## Description détaillée 

L'utilisateur pourra configurer le ou les ressources qu'il souhaite via les propriétés suivantes :

- Ajouter un type nouveau "tilevector" ou terme équivalent disponible en "baselayer" comme en "layer",
- configuration d'une "url" pour aller récupérer les tuiles,
- configuration d'un "styleurl" pour aller récupérer un fichier de style personnalisé (json)

**Comment by Agath21** [comment]
Sujet traité dans l'issue #174
