### ISSUE TITLE
Ajout d'une couche - création - Bouton annuler inutile

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#165]
## Description

Lorsqu'on créé une couche, la couche s'ajoute dans le menu parmis les autres couches, cette liste est masquée par une modal.
Si on clique ensuite sur "Annuler", la nouvelle couche est toujours dans la liste.

Le bouton "Annuler" ne sert donc que pour fermer la modal.

Est-ce Un comportement souhaité ?

## Comportement attendu

Cliquer sur "Annuler" supprime la nouvelle couche + ferme la modal.

## Reproduire

1. Ouvrir studio
2. Cliquer sur "Créer un nouveau projet"
3. Ajouter un titre
4. Cliquer sur "Suivant"
5. Cliquer sur "+ créer"
6. Voir que la nouvelle thématique a été ajoutée
7. Cliquer sur "Annuler"
8. Voir que la nouvelle thématique reste

## Capture

![image](https://user-images.githubusercontent.com/16317988/216977106-ab257673-86a6-4151-9b3c-dcd50716b7d4.png)

**Comment by lecault** [comment]
Issue obsolète avec la disparition de la modal sur les thématiques.
