### ISSUE TITLE
Mode dev - Erreur CORS

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#166]
## Description

En utilisant le backend en local (en faisant tourner flask) on ne peut pas utiliser les géo services / catalogues :

![image](https://user-images.githubusercontent.com/16317988/216993668-633093d5-15cb-49b9-a730-3ae18f82d359.png)

## Reproduire

* Installer mviewerstudio en local (`localhost`)
* Lancer Flask (`flask run` - Accessible en `localhost:5000`)
* Créer une thématique
* Chercher la couche lycée dans le catalogue GeoBretagne
* Voir l'erreur dans la console

**Comment by spelhate** [comment]
Je propose de créer une première implémentation simple d'un proxy python avec une liste blanche

**Comment by spelhate** [comment]
Première implémentation dans la branche feature-166
https://github.com/mviewer/mviewerstudio/compare/master...feature-166
Résultat ici : https://delib.csm.ovh/mviewerstudio/index.html (liste blanche = geobretagne + ows.region-bretagne.fr)
