### ISSUE TITLE
fonds de plan personnalisés

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#172]
> ref #157 

## Description

En tant qu'administrateur,
Je souhaite disposer d'une interface me permettant d'ajouter mon fond de plan,
Afin de voir sur la carte les fonds de plan de mon serveur cartographiques, ou un fond de plan absent de la liste.

**Comment by Agath21** [comment]
## Proposition d'interface et parcours utilisateur

L'ajout d'un fond de plan personnalisé est accessible au sein du module `Application` > Accordéon `Fond de plan` > `"Mode avancé"`

![mstudio_application_FondPlanAdvanced01](https://user-images.githubusercontent.com/22764056/218720859-210f3efd-8482-467c-983e-1e9541619d26.PNG)

En tant qu'utilisateur :

1. J'active l'ajout d'un fond de plan en cliquant sur le bouton `switch` associé
2. Je sélectionne le type de fond de plan (liste déroulante avec les types suivants : `OSM, WMTS, WMS, vector-tms`)
3. En fonction du type sélectionné, je renseigne les champs mis à disposition

![mstudio_application_FondPlanAdvanced02](https://user-images.githubusercontent.com/22764056/218720896-db1faf2c-dcdc-496e-aca5-6d1c6a86d1f6.PNG)
_Exemple d'interface avec le type "Vector-TMS"_

## Spécifications techniques

- Pour le moment, il est prévu de pouvoir ajouter seulement 1 fond de plan personnalisé 
- Seuls les paramètres principaux (et obligatoires) tels que définis dans [la documentation](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_baselayers.html) vont être intégrés au studio
- L'affichage des paramètres est conditionné au type de fond de plan sélectionné dans la liste. Ils sont définis ci-dessous : 

| Paramètres obligatoires | Type       | OSM | WMTS | WMS | Vector-TMS |
|-------------------------|------------|-----|------|-----|------------|
| type                    | texte      | x   | x    | x   | x          |
| id                      | texte      | x   | x    | x   | x          |
| label                   | texte      | x   | x    | x   | x          |
| title                   | texte      | x   | x    | x   | x          |
| thumbgallery            | url        | x   | x    | x   | x          |
| url                     | url        | x   | x    | x   | x          |
| styleurl                | url (JSON) |     |      |     | x          |
| layers                  | texte      |     | x    | x   |            |
| format                  | texte      |     | x    | x   |            |
| visible                 | bool       | ?   | ?    | ?   | ?          |
| attribution             | texte      | x   | x    | x   | x          |
| style                   | texte      |     | x    |     | x          |

## Interrogation

@Gaetanbrl  @spelhate  @lecault 

### Gestion du paramètre `visible`
**Fonction :** Ce paramètre permet d'afficher un fond de plan au démarrage. Il s’agit d’un paramètre exclusive et donc une seule couche de fond peut être affichée sur la carte. 

**Fonctionnement actuel :** il est géré via une liste déroulante avec la liste des fonds de plan de base 
![image](https://user-images.githubusercontent.com/22764056/218725721-63b08b5a-9c4c-45fa-a455-93a391c2bc8b.png)


**Question :** Lorsque l'on ajoute un fond de plan personnalisé, doit-on également l'ajouter à cette liste pour pouvoir l'afficher par défaut ? OU Il n'est pas possible d'activer un fond de plan personnalisé par défaut ?

**Comment by Gaetanbrl** [comment]
> OU Il n'est pas possible d'activer un fond de plan personnalisé par défaut ?

Je dirait que ca devrait prendre en compte toutes les possibilités de mviewer.
Si mviewer contient un fond de plan qui n'est pas dans la liste, et qui est celui par défaut on devrait le voir.

**Comment by Agath21** [comment]
> > OU Il n'est pas possible d'activer un fond de plan personnalisé par défaut ?
> 
> Je dirait que ca devrait prendre en compte toutes les possibilités de mviewer. Si mviewer contient un fond de plan qui n'est pas dans la liste, et qui est celui par défaut on devrait le voir.

Ok donc si on ajoute un fond de plan personnalisé, ce fond de plan se rajoute également dans la liste déroulante "Fond de plan au démarrage" avec le nom indiqué par l'utilisateur ?

**Comment by Gaetanbrl** [comment]
En fait ce raisonnement doit être appliquer je suppose : 

1. Ajouter un fond de plan
2. Sauvegarder le XML
3. Télécharger le XML
4. Voir dans le XML que le fond de plan a été ajouté
5. Ouvrir le XML avec studio
6. Voir le fond de plan ajouté précédemment
7. Supprimer l'application de studio
8. Importer le XML réalisé avant
9. Voir le fond de plan

**Comment by Gaetanbrl** [comment]
C'est le `Cas de test` plus qu'un parcours utilisateur.

**Comment by Agath21** [comment]
Ah ok dsl ... Je valide

**Comment by Gaetanbrl** [comment]
Fonctionnel pour les TMS. A tester avec les autres formats.

**Comment by Agath21** [comment]
Tester avec la BD Topo en Vector-TMS, c'est fonctionnel ! Merci @Gaetanbrl 

![image](https://user-images.githubusercontent.com/22764056/219302723-9aaafb2c-61d6-4795-a0de-ce056c8959fe.png)

**Comment by Gaetanbrl** [comment]
Evolution à prévoir : 

- validation des champs
- Masquer / afficher le bouton "valider" selon la validation est bonne (ou au moins seulement si une valeur de type est sélectionnée)

**Comment by Agath21** [comment]
+ ajout d'une alerte

**Comment by lecault** [comment]
Tests effectuées sur la branche issue-157

- Test WMS GéoBretagne OK
	`<baselayer visible="false" label="OpenStreetMap GéoBretagne" thumbgallery="https://geobretagne.fr/pub/logo/161_osmfr.jpg" title="OpenStreetMap GéoBretagne" id="osm_default" styleurl="" style="" layers="osm:map" attribution="OSM" format="image/png" url="https://osm.geobretagne.fr/gwc01/service/wms" type="WMS"  ></baselayer> `

- Test WMTS IGN KO
`<baselayer visible="false" label="IGN" thumbgallery="https://geobretagne.fr/pub/logo/099_ign.jpg" title="" id="ortho10" styleurl="" style="normal" layers="ORTHOIMAGERY.ORTHOPHOTOS" attribution="IGN" format="image/jpeg" url="https://wxs.ign.fr/essentiels/geoportail/wmts" type="WMTS"  ></baselayer> 
`	
  - Pour que ça fonctionne, ajout des options matrixset="PM" fromcapacity="false"
  - Solution proposée : ajout d'un bouton on/off (on par défaut) pour paramètre fromcapacity (Lire capacité). Si on met à false, affichage de l'option matrixset (valeur PM suggérée)
- Test TMS KO :  il ne veut pas ajouter la connexion avec les paramètres suivants
  - https://wxs.ign.fr/topographie/geoportail/tms/1.0.0/BDTOPO/{z}/{x}/{y}.pbf 
  - https://wxs.ign.fr/static/vectorTiles/styles/BDTOPO/routier.json
	
- Je propose une modification de l'ordre d'affichage
	- ID / Libelle
	- URL / id technique
	- Attribution / Sous - titre
	- aperçu / format d'image
- Corriger l'orthographe Lien vers la vignette d'aperçu
- Ajout de l'option opacity qui me semble très utile

**Comment by Gaetanbrl** [comment]
> Test WMTS IGN KO

OK on a été induit en erreur avec la config qui ne dit pas que c'est obligatoire (voir section `config minimale`).

> Ajout de l'option opacity qui me semble très utile

Je pense que c'est une issue à créer, cette évolution n'étant pas présente dans les paramètres de prestation (voir commentaire des spécifications).

>  Je propose une modification de l'ordre d'affichage

@spelhate ca te convient ?

> Test TMS KO

OK vu. Les URLs passent par la méthode checkurl qui test le lien en passant par le /proxy et retourne une erreur 500.
Il faut revoir le contrôle sur ces champs.
On ne sait pas pourquoi mais auparavant cela fonctionné, probablement car on avait pas encore /proxy quand on a développé ces champs.

**Comment by Agath21** [comment]
Corrections à réaliser : 

- [ ] WMTS : ajout des options matrixset="PM" fromcapacity="false"
- [ ] Modifier l'ordre des paramètres

**Comment by spelhate** [comment]
Test WMTS Géobretagne ok

`<baselayer visible="false" label="Costel 2005" thumbgallery="https://geobretagne.fr/mviewer/img/basemap/ir.jpg" title="Occupation des sols en Bretagne en 2005 - COSTEL" id="costel_2005_dreal" styleurl="" style="Costel_raster" layers="costel:costel_2005_dreal" attribution="GéoBretagne" format="image/png" url="https://geobretagne.fr/geoserver/gwc/service/wmts" type="WMTS"  ></baselayer> 
`

**Comment by Agath21** [comment]
@spelhate est-il nécessaire de rajouter les paramètres `matrixset="PM" fromcapacity="false"` ?

**Comment by Agath21** [comment]
> > @spelhate est-il nécessaire de rajouter les paramètres `matrixset="PM" fromcapacity="false"` pour le WMTS ?
> 
> Oui c'est plus propre.

C'est en cours :)

**Comment by lecault** [comment]
Test ok WMTS IGN

**Comment by Agath21** [comment]
> En TMS il manque le lien vers la vignette d'aperçu.

Ok, corrigé ce jour

**Comment by spelhate** [comment]
Testé sur jdev : Le paramètre "**Construire la couche à partir des capacités du service**" devrait être une checkbox (oui/non) plutôt qu'un champ texte.

**Comment by Agath21** [comment]
> Testé sur jdev : Le paramètre "Construire la couche à partir des capacités du service" devrait être une checkbox (oui/non) plutôt qu'un champ texte. Et on garde non par défaut.

![image](https://user-images.githubusercontent.com/22764056/228490768-946a2a9a-87d8-4e29-969f-55d93c042052.png)

Développé sur la branch `fix-172` et reversé sur `develop-meg`

**Comment by Gaetanbrl** [comment]
> Développé sur la branch fix-172 et reversé sur develop-meg

Merci @Agath21

**Comment by spelhate** [comment]
Suite aux derniers tests effectués, le paramètre **fromcapacity**  pour les couches WMTS apparait finalement obsolète au regard des dernières versions des services WMTS fournies par l'IGN. De plus, ce paramètre si activé génère des erreurs avec les couches IGN. Je propose de le déprécier dans mviewer. Je vais faire une issue dans ce sens.
Dans mviewer, `fromcapacity="true"` = bug. Nous proposons donc de masquer le bouton  "fromcapacity".

**Comment by Gaetanbrl** [comment]
> Dans mviewer, fromcapacity="true" = bug. Nous proposons donc de masquer le bouton "fromcapacity

Fait ==> Issue à fermer @Agath21 @spelhate ?

**Comment by spelhate** [comment]
On ferme.
