### ISSUE TITLE
Identifier la version Mviewer

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#173]
> ref #157 

## Description

En tant qu'administrateur de carte,
Je souhaite pouvoir connaître la version mviewer compatible avec la carte générée par mviewer studio,
Afin de pouvoir utiliser la bonne version de mviewer compatible avec les paramètres de ma carte.

## Spécifications

Actuellement, la version mviewerstudio est déjà intégrée dans les métadonnées d'un XML généré via mviewerstudio.
Cependant, il serait bien d'ajouter la version mviewer pour savoir avec quel mviewer la carte générée est compatible afin de pouvoir utiliser dans mviewer les paramètres compatibles.

Sans cette version, il est possible qu'un utilisateur test une carte dans un mviewer d'une version antérieure et qu'il ne comprenne pas pourquoi les paramètres d'une version récente ne fonctionne pas sur sa version antérieure.

**Comment by Agath21** [comment]
> Réalisé et disponible sur la branche develop-meg : 


L'administrateur indique dans la configuration du studio, la version mviewer utilisée via le paramètre `mviewer_version.`

La version mviewer est ensuite disponible dans l'ensemble des config.xml généré : 

![image](https://user-images.githubusercontent.com/22764056/224932485-52ad49ce-0484-433f-a07d-d4e90938ca5e.png)

**Comment by Gaetanbrl** [comment]
Issue couverte -> Je clos
