### ISSUE TITLE
Ajouter une couche via ses paramètres directement

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#174]
> ref #157 

## Description

En tant que géomaticien,
Je souhaiterai pouvoir ajouter un flux WMS via ses paramètres sans utiliser de serveurs cartographique et sans utiliser de catalogue,
Afin de pouvoir ajouter un type TMS ou un WMS via les paramètres comme le propose mviewer.

## Spécifications

Cette issue est complexe et nécessite une réflexion sur :

- l'interface existante (maquettes)
- le code existant
- le contenu

Actuellement, les paramètres sont compatibles avec un WMS. Si on ajoute d'autres types, il est nécessaire de masquer ou afficher les paramètres selon le type. Hors, la fenêtre d'affichage des paramètres d'une couche ne le permet pas actuellement.

Il faut donc revoir le code de cette fenêtre et créer un mapping entre un type et ses paramètres, en sachant que certains paramètres sont communs à un autre type.

Les types potentiellement intégrables dès aujourd'hui car disponible dans mviewer sont : 

- WMS
- TMS

Les types suivants sont des candidats pour être ajoutés à l'avenir : 
- WFS
- Sensorthings
- COG

**Comment by Agath21** [comment]
Note : Réaliser un tableau avec les paramètres à afficher en fonction du type de donnée

**Comment by lecault** [comment]
Ok pour le principe.
Il faudrait effectivement ajouter la possibilité d'ajouter des types différents (exemple customlayers) et afficher les champs obligatoires pour chaque type à la saisie.

Je trouve le badge une bonne idée. 

Concernant la modale Paramètres de la donnée, tu proposes pour chaque option de savoir pour quels types elles sont utiles ?
D'ailleurs ça me fait penser que je n'ai jamais utilisé mviewerstudio autre que WMS. 
Concernant cette partie, il faudrait tester le comportement sur un autre type avant d'engager des frais, ça me semble une utilisation marginale actuellement (public expert).

**Comment by spelhate** [comment]
> Les types suivants sont des candidats pour être ajoutés à l'avenir :
> 
>     * WFS
> 
>     * Sensorthings
> 
>     * COG

On pourrait également ajouter à termes : 

- customlayer
- import
- geojson

**Comment by Gaetanbrl** [comment]
> import

ca correspond à quoi ? un fichier csv ?

**Comment by spelhate** [comment]
> > import
> 
> ca correspond à quoi ? un fichier csv ?

Oui.

**Comment by spelhate** [comment]
> Note : Réaliser un tableau avec les paramètres à afficher en fonction du type de donnée en essayant d'indiquer dans quel onglet il se situe et avec quel composant (input / select / switch ...)
> 
> Doc : https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_layers.html

D'accord - tout en précisant les champs obligatoires et optionnels. On doit pouvoir démarrer à partir de la doc en principe.

**Comment by spelhate** [comment]
👍 +1 pour le badge

Ok pour moi.

**Comment by Agath21** [comment]
## Avancement 

- [ ] Modifier la modale "Ajouter une donnée" en ajoutant un système d'onglets : "Depuis un catalogue" / "Via des paramètres"
- [ ] Ajouter les composants d’interfaces permettant de renseigner les paramètres de la nouvelle couche avec une configuration minimale. L’affichage des paramètres est dynamique selon le type sélectionné dans la liste déroulante : 
- [ ] Affichage d'une alerte si les champs ne sont pas renseignés
- [ ] Création d’un nouvelle couche dans la thématique avec les paramètres renseignées
- [ ] Ouvrir la modale « Paramètres de la donnée » pour pouvoir modifier la nouvelle couche
- [ ] Personnaliser l’affichage des paramètres au sein de la modale en fonction du type de couche 
- [ ] Afficher un badge indiquant le type de couche

**Comment by Agath21** [comment]
## Scénarios de mise en place pour la modale des paramètres

Actuellement, lorsqu’on ouvre les paramètres d’une donnée, on ouvre la modale `id="mod-layerOptions"` avec l’ensemble des paramètres propres au type de couche WMS. La structure de cette modale et ces composants sont définis en dur dans le fichier `index.html`. 

Avec l’ajout de nouveaux types de couche (ici Vector-TMS), certains paramètres ne sont plus utiles et il est nécessaire d’en rajouter d’autres propres au type sélectionné. Pour personnaliser l’affichage des composants, plusieurs solutions techniques peuvent être envisagées : 

### Solution 1 : 

- On conserve la modale actuelle et on rajoute les nouveaux paramètres en surchargeant l’`index.html`. 

- On ajoute des classes html avec le nom du type pour les paramètres spécifiques aux types. Exemple : 

```
 <h6 i18n="modal.layer.styles" class="**wms**" >Style(s) de la donnée disponible(s)</h6>
 <div class="row mt-3 **wms**" id="frm-lis-styles"></div>
```

- On gère ensuite l’affichage ou non des paramètres à l’aide du` .js`

**Avantages :** Mise en place rapide et peu coûteuse 
**Inconvénient :** Surcharge de l’index.html

### Solution 2:

- On crée une modale générique « Paramètres de la donnée » vide
- On crée ensuite des classes pour les types de couches définissant les paramètres associés
- En fonction du type de la couche, la modale est peuplée par les paramètres : communs + propres au type

**Avantages :** souplesse de la méthode pour rajouter des types et allègement de l’index 
**Inconvénient :** nécessite de revoir l’ensemble du code pour cette partie (coûteux) + difficulté pour gérer la position des composants dans l’IHM. 
_En effet actuellement on utilise les classes bootstrap row / col avec une composition personnalisée. Pour cette méthode l’IHM est à retravailler complétement en la simplifiant avec un input par ligne, les un après les autres + suppression des accordéons ou composants plus spécifiques_ 

Des avis ? @spelhate @Gaetanbrl

**Comment by Agath21** [comment]
Développements réalisés sur la branch issue-174 et mergés sur [develop-meg](https://github.com/jdev-org/mviewerstudio/tree/develop-meg) -> à tester

**Comment by spelhate** [comment]
ok pour la solution 1

**Comment by spelhate** [comment]
Retours test avec le montage d'une couche WMS geoserver.
ok mais il faudrait activer 2 paramètres par défaut :

- Interrogation standard
- mode tuilé

**Comment by lecault** [comment]
Test sur une couche WMS issue de carmen KO à cause du proxy.
Voici les paramètres à tester : 
id : ZNIEFF_2_marine
url : http://ws.carmen.application.developpement-durable.gouv.fr/WMS/10/Nature_Paysage

**Comment by lecault** [comment]
Test TMS ok

**Comment by lecault** [comment]
Après avoir ajouté une couche avec des paramètres personnalisés, on veut ajouter une couche depuis un catalogue, on a un message qui dit "informations manquantes".

Le problème vient du fait que la page ajout par paramètre n'a pas été réinitialisée.

**Comment by Agath21** [comment]
Retours à corriger : 

- [ ] Activer par défaut l'interrogation (WMS)
- [ ] Activer par défaut le mode tuilé (WMS)
- [ ] Gérer la réinitialisation des paramètres

**Comment by Agath21** [comment]
> Après avoir ajouté une couche avec des paramètres personnalisés, on veut ajouter une couche depuis un catalogue, on a un message qui dit "informations manquantes".
> 
> Le problème vient du fait que la page ajout par paramètre n'a pas été réinitialisée.

@lecault, je n'arrive pas à reproduire ton erreur, peux-tu développer ton cas d'usage si tu le reproduis systématiquement ? Merci :)

**Comment by Agath21** [comment]
Ok merci pour le détail. 
Effectivement, ce cas d'usage n'est pas géré puisque d'un point de vue interface, on change juste d'onglet, les paramètres restent actifs tant que l'utilisateur n'a pas validé.

**Comment by lecault** [comment]
Je viens de tester les corrections sur le studio de jdev, c'est ok pour moi.

**Comment by lecault** [comment]
Un petit commentaire : c'est super pratique de pouvoir ajouter une couche comme cela en 3 paramètres :).
Une idée d'amélioration qui pourra faire l'objet d'une issue : pouvoir récupérer l'identifiant / le titre de la donnée depuis un getcapabilities pour un WMS.

**Comment by Gaetanbrl** [comment]
>Une idée d'amélioration qui pourra faire l'objet d'une issue : pouvoir récupérer l'identifiant / le titre de la donnée depuis un getcapabilities pour un WMS.

@lecault peux-tu ouvrir une issue pour ne pas oublier cette fonctionnalité intéressante ?
