### ISSUE TITLE
Style des données non actualisé - Recherche dans un catalogue WMS

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewerstudio#175]
Lors de la refonte de l'interface du mviewer studio, le style des données renvoyées au sein d'un catalogue du type wms n'a pas été actualisé.

Catalogue WMS :

![image](https://user-images.githubusercontent.com/22764056/218744752-db7e9f71-47c3-4c65-a92c-38e1ff84abf5.png)

Catalogue CSW (interface souhaitée) : 

![image](https://user-images.githubusercontent.com/22764056/218744928-6a92b93d-ddc6-41de-a823-09d00e09d1e2.png)

**Comment by Agath21** [comment]
Réalisé finalement dans la branche https://github.com/jdev-org/mviewerstudio/tree/issue-157

**Comment by spelhate** [comment]
> Réalisé finalement dans la branche https://github.com/jdev-org/mviewerstudio/tree/issue-157

Ok.
