### ISSUE TITLE
MEG - VSR - Ouverture d'une app dans le studio depuis mviewer 

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewerstudio#185]
### Description du bug 
Lorsque l'on ouvre l'édition d'une application depuis le mviewer (éditer dans studio), le mviewer studio apparaît dans un nouvel onglet mais sur le page d'accueil et l'URL semble étrange : 
http://test-sig5/mviewerstudio/index.html#http://test-sig5/mviewer/apps/store/39a9d224040f/preview/c505368e-c412-11ed-8811-00505698285b.xml 

### Comportement souhaité
1 . Je clique sur "Editer dans studio" depuis mon application mviewer
2 . Le mviewer studio s'ouvre au sein d'un nouvel onglet 
3 . Le module studio est automatiquement visible et peuplé avec les paramètres de l'application

**Comment by Gaetanbrl** [comment]
modification à faire dans la doc :

https://github.com/mviewer/mviewer/issues/747#issuecomment-1504762731

**Comment by Gaetanbrl** [comment]
Après test,
La génération d'une application avec l'option  avancée `Ouvrir la carte dans le studio` ne permet pas d'avoir une URL directement utilisable dans mviewer.

**Etapes :** 

1. créer une application dans studio et lui donner un titre
2. Cocher le mode avancé
3. Cocher `Ouvrir la carte dans le studio`
4. Sauvegarder
5. Cliquer sur Prévisualiser
6. Cliquer sur la clé à molette à droite "Modifier la carte"
7. Voir que le lien est erroné et ne contient pas `?xml=` permettant au studio d'ouvrir le XML

> http://localhost:5000/index.htmlhttp://127.0.0.1:5051/apps/store/public/8b38b7068b1a/preview/4d89adf4-fa0b-11ed-b4b0-00155d38b60b.xml

8. Modifier l'URL pour rajouter le paramètre `?xml=` manquant à la fin de `index.html`
9. Tester l'URL
10. Voir que le studio ouvre bien le fichier


J'ai donc modifié le code de studio (voir commit précédent mon commentaire) et j'obtiens à présent un lien correct à l'étape 7 précédente (résultat OK).

**Comment by spelhate** [comment]
Ok pour moi.
