### ISSUE TITLE
Manque pramamétrage du proxy ajax dans mviewerstudio

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#186]
Actuellement, mviewerstudio génère des configurations xml avec un proxy renseigné.

```xml
<proxy url="/proxy/?url="/>
```

Ce paramétrage devrait être disponible via mviewerstudio (Champ texte)

**Comment by spelhate** [comment]
Comment peut-on désactiver l'utilisation du proxy avec mviewer ?
Si au moment de l'enregistrement, le champ proxy est vide, studio affecte la valeur définie par défaut. Ce qui ne convient pas dans ce cas.

Ce qu'on souhaite : 

- Dans Studio, affichage par défaut du proxy tel que défini dans le config.json de studio
- Si l'utilisateur efface cette valeur, studio enregistre la conf avec `<proxy url=""/>`

**Comment by Gaetanbrl** [comment]
@spelhate voir travaux en cours : 

https://github.com/jdev-org/mviewerstudio/blob/develop-meg/index.html#L252

**Comment by Gaetanbrl** [comment]
- [ ] rajouter au code ci-dessous un `else`  pour définir un proxy vide : 

`else {<proxy url = "">}`

**Comment by lecault** [comment]
Je viens de tester si on vide le proxy c'est ok.

> * Dans Studio, affichage par défaut du proxy tel que défini dans le config.json de studio

Par contre pour ce point là je ne suis pas sur. Par défaut lors de la création d'une nouvelle application, le proxy est vide :
<proxy url=""/>

**Comment by Gaetanbrl** [comment]
> Par contre pour ce point là je ne suis pas sur. Par défaut lors de la création d'une nouvelle application, le proxy est vide

Quel est l'état de la valeur proxy dans la config json du studio ?

**Comment by lecault** [comment]
c'est chez vous je ne sais pas :)

**Comment by Gaetanbrl** [comment]
je ne suis pas sur de comprendre ta remarque du coup...
Chez nous c'est vide. Sinon tu verrai la valeur dans l'input je crois.. et sinon ca ne marcherait pas, vu que c'était le problème avec une valeur non vide dans le config json ;)

**Comment by lecault** [comment]
Tu as raison suis perdu avec ce proxy..

**Comment by spelhate** [comment]
Le comportement attendu  : 

-  définition dans config.json d'un proxy (utilisé à la fois pour studio et pour la configuration xml par défaut d'une application mviewer)
- Si défini dans config.json, affecte la valeur du proxy au formulaire studio. ex` "monproxy?url="` et produit un xml mviewer avec  `<proxy url="monproxy?url="/>`
- si non défini dans config.json ou si effacé dans le formulaire studio => produit un xml avec `<proxy url=""/>`

**Comment by Gaetanbrl** [comment]
@spelhate @lecault issue à ferme je pense (si tests OK).

**Comment by Gaetanbrl** [comment]
> On souhaite une cohérence entre l'IHM et le xml produit.

Vu, c'est noté.

**Comment by Gaetanbrl** [comment]
@spelhate j'avais en réalité déjà apporté la modification sur ma branche issue-160 : 

https://github.com/jdev-org/mviewerstudio/blob/issue-160/lib/mv.js#L1184-L1186

A reporter dans issue-161-rebase donc.

**Comment by Gaetanbrl** [comment]
> A reporter dans issue-161-rebase donc.

En fait j'ai un doute...

**Comment by Gaetanbrl** [comment]
@spelhate correctif à tester sur branche issue-161-rebase et visible sur https://gis.jdev.fr/mviewerstudio/index.html#

**Comment by Gaetanbrl** [comment]
En attente de retour de @spelhate ou @lecault

**Comment by spelhate** [comment]
> Le comportement attendu :
> 
>     * définition dans config.json d'un proxy (utilisé à la fois pour studio et pour la configuration xml par défaut d'une application mviewer)
> 
>     * Si défini dans config.json, affecte la valeur du proxy au formulaire studio. ex` "monproxy?url="` et produit un xml mviewer avec  `<proxy url="monproxy?url="/>`
> 
>     * si non défini dans config.json ou si effacé dans le formulaire studio => produit un xml avec `<proxy url=""/>`

Le dernier point ne fonctionne pas. On a toujours le proxy défini dans le config.json.
Testé sur branche develop-meg

**Comment by Gaetanbrl** [comment]
> > Le comportement attendu :
> > ```
> > * définition dans config.json d'un proxy (utilisé à la fois pour studio et pour la configuration xml par défaut d'une application mviewer)
> > 
> > * Si défini dans config.json, affecte la valeur du proxy au formulaire studio. ex` "monproxy?url="` et produit un xml mviewer avec  `<proxy url="monproxy?url="/>`
> > 
> > * si non défini dans config.json ou si effacé dans le formulaire studio => produit un xml avec `<proxy url=""/>`
> > ```
> 
> Le dernier point ne fonctionne pas. On a toujours le proxy défini dans le config.json. Testé sur branche develop-meg

OK à corriger.

**Comment by Gaetanbrl** [comment]
Cas de test : 

- [ ]  Créer une app et voir la valeur du proxy reprise depuis le fichier config.json - Test OK

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/e0690ce7-c07c-442d-b45f-d5626e5ce3f1)

- [ ] Sauvegarder et voir dans le XML la valeur par défaut reprise du config.json - Test OK

`<proxy url="proxy/?url="/>`

- [ ] Changer la valeur et voir cette nouvelle valeur dans le XML - Test OK

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/fbdbcf1c-15ae-4d18-8f12-658c8c65caa6)

`<proxy url="nouveauproxy/?url="/>`

- [ ] Supprimer la valeur du champ et voir la bonne valeur vide dans le XML à la sauvegarde - Test OK

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/61a08930-c0bc-4df2-ae7e-f04c4c01ea60)

`<proxy url=""/>`

**Comment by lecault** [comment]
C'est ok pour moi
