### ISSUE TITLE
MEG-161 Amélioration panneau publication #161

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#192]
- [x] lien de publication (lecture seule). Actuellement on peut éditer la zone de texte
- [x] code iframe : remplacer les simples quotes par des doubles quotes

**Comment by Gaetanbrl** [comment]
Correction visible dans la branche **jdev-org/issue-161-rebase** uniquement.

**Comment by lecault** [comment]
Ok pour moi
