### ISSUE TITLE
MEG-158 Amélioration panneau historique des modifications #158

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#193]
En mode avancé actuellement on a ça : 
![image](https://user-images.githubusercontent.com/1793792/232441489-1989d07a-27fe-48cf-afac-07f138efd238.png)

Dans le cas présent, on a deux versions publiées, mais une seule apparaît comme publiée (La première) car nous n'avons pas dépublié entre temps.
/!\ Si on publie dans dé-publier préalablement rien n'indique qu'une version est publiée.

### ce qu'on souhaite

- [ ] Distinguer la version publiée active (s'il y en a une) -> Fond orange.
- [ ] Distinguer toutes les versions publiés (tag imagette dédié) même si on ne dé-publie pas avant de republier.
- [ ] Publier = nouvel enregistrement ?

**Comment by Gaetanbrl** [comment]
> test lié à issue #158 (close)

**Evolution hors besoin / spécifications initiales qui demandait de voir le statut d'une application et non pas les versions**

Rappel du fonctionnement spécifié :

>On peut publier une première fois une application et modifier le fichier sans republier. Dans ce cas, les modifications ne sont pas liées à la version publiée. Il faut alors recliquer sur "publier" pour que les dernières modifications soient visible dans la version "publiée".

Reste cependant à détailler pour être certain de cerner les besoins : 

**- Distinguer la version publiée active** 

@spelhate est-ce bien ta demande qu'en tant qu'utilisateur : 

> Je souhaite pouvoir voir à quelle sauvegarde (version) correspond la version actuellement publiée ?

**- Distinguer toutes les versions publiées**

Actuellement en effet, on a que la première publication et la dépublication (infos déjà hors cadre du besoin initial).

Ta demande est-elle bien la suivante :

1. Je souhaite de voir toutes les fois où il a été cliqué sur "publié" sans avoir "dépublier" auparavant ?
2. Je souhaite savoir quelle changement est intégré dans la version actuellement publiée ?

**- Publier = nouvel enregistrement ?**

A chaque fois que l'on clique sur "publier" => On va sauvegarder le XML, notamment pour garder l'information de la meta `dc:relation` à jour dans le xml de brouillon et de publication.

**Comment by Gaetanbrl** [comment]
Proposition @spelhate :

![image](https://user-images.githubusercontent.com/16317988/232701952-f73ec0c9-a82a-44bb-885d-43357e60c258.png)

**Comment by Gaetanbrl** [comment]
Suite au correctif sur la branche issue-161-rebase (et uniquement cette branche !) : 

Aperçu lorsqu'on publie une version (badge **En ligne**) mais qu'on a rajouté ensuite une modification qui n'est pas encore publiée (cochée comme **active** en **brouillon**). On voit notamment toutes les versions ou modifications qui sont dans la version actuellement publiée (badge **En ligne**) :

![image](https://user-images.githubusercontent.com/16317988/234200053-c8b69886-2bd7-45ff-8f0a-8a308d3dd084.png)

Après avoir recliqué sur "Publier" on voit qu'on est bien ISO entre la version **brouillon** et la version **En ligne** car la ligne en orange (= version publiée) est bien la ligne **active** (cochée) :

![image](https://user-images.githubusercontent.com/16317988/234200657-d2f0a994-ea3a-44fa-aae3-8cfb4c515110.png)

**Comment by lecault** [comment]
Mise en évidence dernière version publiée => ok
Enregistrement à la publication => ok
Distinguer les versions publiées => juste écrit version publiée pas de tag spécifique. Pas bloquant pour ma part.

Il y a un truc qui me perturbe c'est le fait d'avoir en ligne sur toutes les versions antérieures (ça me dérange pas sur brouillon).
Car si je reviens sur une version antérieure avec le badge en ligne, elle n'est pas automatiquement publiée.
Proposition : n'avoir le badge en ligne ou brouillon que sur la dernière version.

cas 1 : 
![image](https://user-images.githubusercontent.com/5269430/235181404-7b0583c9-2aab-496c-92bf-e61f6189ab80.png)

cas 2 : 
![image](https://user-images.githubusercontent.com/5269430/235181628-4649ad54-a7c5-491d-95f0-0454b1e78ffb.png)

=> à valider avec @spelhate

**Comment by spelhate** [comment]
> Il y a un truc qui me perturbe c'est le fait d'avoir en ligne sur toutes les versions antérieures (ça me dérange pas sur brouillon).
> Car si je reviens sur une version antérieure avec le badge en ligne, elle n'est pas automatiquement publiée.
> Proposition : n'avoir le badge en ligne ou brouillon que sur la dernière version.

Je pense la même chose.

**Comment by Gaetanbrl** [comment]
Modification disponible sur `gis.jdev.fr` branche `issue-160` : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/1e0fa866-f3ec-45cb-9261-301ac14d1354)

**Comment by Gaetanbrl** [comment]
A fermer @spelhate @lecault ?

**Comment by spelhate** [comment]
Ok pour moi.
