### ISSUE TITLE
MEG - VSR - 161 Harmonisation nommage urls #161

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#194]
Les règles de nommages des urls entre le mode brouillon et publié ne sont pas les mêmes.

Exemple en mode brouillon : 
https://gis.jdev.fr/mviewer/#store/Geob/3f46660be2f5/lyc_es_de_bretagne

Exemple en mode publié : 
https://gis.jdev.fr/mviewer/#public/Geob/lycees_de_bretagne

Propostion : utiliser les règles du mode publié pour le mode brouillon

**Comment by Gaetanbrl** [comment]
Correctif appliqué dans la branche **jdev-org/issue-161-rebase** uniquement.

**Comment by lecault** [comment]
URL harmonisée mais regex insatisfaisante #195.

**Comment by Gaetanbrl** [comment]
à traiter avec #195

**Comment by Gaetanbrl** [comment]
a traiter dans #195
