### ISSUE TITLE
MEG - VSR - 161 regex url création application

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#195]
branche issue-161-rebase
Je créé une application avec comme titre écluse.

Actuellement l'url générée est : https://gis.jdev.fr/mviewer/#store/Geob/5826b342b758/_cluse

Le souhait est d'avoir une url comme ceci : https://gis.jdev.fr/mviewer/#store/Geob/5826b342b758/ecluse

Au niveau de la regex, les caractères accentués sont remplacés par le caractère sans accents.
Ici, écluse => ecluse

**Comment by Gaetanbrl** [comment]
Je viens de voir que dans studio il y a une méthode faite par @bchartier qui liste les caractères spéciaux (vu que les regex de base ce n'est qu'un mécanisme pour trouver des caractères dans une chaîne) : 

https://github.com/jdev-org/mviewerstudio/blob/master/lib/slug.js#L9

Exemple avec cette methode : 

```
slugify("écluse€ de br€tagne!")
==> 'ecluse-de-brtagne'
```

ca te conviendrai @lecault ?

**Comment by Gaetanbrl** [comment]
A noter que ce code semble provenir de : 

https://gist.github.com/codeguy/6684588

Il faudra qu'on rajoute l'URL du dépôt dans le fichier directement pour nommer la source.

**Comment by lecault** [comment]
> Je viens de voir que dans studio il y a une méthode faite par @bchartier qui liste les caractères spéciaux (vu que les regex de base ce n'est qu'un mécanisme pour trouver des caractères dans une chaîne) :
> 
> https://github.com/jdev-org/mviewerstudio/blob/master/lib/slug.js#L9
> 
> Exemple avec cette methode :
> 
> ```
> slugify("écluse€ de br€tagne!")
> ==> 'ecluse-de-brtagne'
> ```
> 
> ca te conviendrai @lecault ?

Oui ça me convient :)

**Comment by Gaetanbrl** [comment]
A partir du titre suivant : 

**lYcées de Br€tâgne!**

La RegEx apportée ce jour dans le JS et le Python permet d'avoir un nom de fichier identique : 

- Fichier XML en `publication `(prod)  : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/48e5ecb5-c093-471d-9f01-5be45eceed34)

- Fichier XML `brouillon `: 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/3ac8363b-6652-4786-a50f-92424c4790c3)

**Comment by lecault** [comment]
ok pour moi :)
