### ISSUE TITLE
MEG-159 Enregistrement de l'option d'affichage d'une thématique externe non persistant

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#199]
A la réouverture dans Studio d'une application, ce paramétrage si défini précédemment est perdu. Testé sur issue-161-rebase

![image](https://github.com/mviewer/mviewerstudio/assets/1793792/1d15b750-37c1-47bb-8a62-b64c3172382a)

Reproduit sur gis.jdev

**Comment by spelhate** [comment]
On a l'impression que ce module sait écrire le paramètre mais pas le lire dans un xml.

**Comment by Gaetanbrl** [comment]
> On a l'impression que ce module sait écrire le paramètre mais pas le lire dans un xml.

On va regarder ca merci du retour.

**Comment by Agath21** [comment]
Effectivement, le paramètre `layersvisibility` n'était pas pris en compte lors de l'ouverture d'un projet existant. Le problème est corrigé sur l'`issue-161-rebase`.

**Comment by Gaetanbrl** [comment]
@spelhate @lecault à fermer ?

**Comment by spelhate** [comment]
Non. Il y a encore un bug.
1) création d'une application avec 3 thématiques externes (option affichage des couches, option affichage par défaut et masquage des couches) > Enregistrement > Pévisualisation Ok.
2) Réouverture de l'application > Les paramètres sont bien affichés dans l'IHM de studio pour les 3 thématiques externes. ->
3) Prévisualisation KO. Les paramètres ne sont pas appliqués. Idem pour le téléchargement du xml  où le paramètre layersvisibility est à `undefined`
```xml
<themes mini="false"> 
    <theme id="education" url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml" name="Education et formation" collapsed="true" icon="false" layersvisibility="undefined"> 
    </theme> 
    <theme id="transport" url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/transport/transports.xml" name="Transport" collapsed="true" icon="false" layersvisibility="undefined"> 
    </theme> 
    <theme id="inventaire" url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/patrimoine/patrimoine.xml" name="Inventaire du patrimoine" collapsed="true" icon="false" layersvisibility="undefined"> 
    </theme> 
</themes>
```
Je fais une nouvelle issue VSR

**Comment by Gaetanbrl** [comment]
OK @spelhate je me l'assigne.

**Comment by Agath21** [comment]
> Non. Il y a encore un bug.
> 
> 1. création d'une application avec 3 thématiques externes (option affichage des couches, option affichage par défaut et masquage des couches) > Enregistrement > Pévisualisation Ok.
> 2. Réouverture de l'application > Les paramètres sont bien affichés dans l'IHM de studio pour les 3 thématiques externes. ->
> 3. Prévisualisation KO. Les paramètres ne sont pas appliqués. Idem pour le téléchargement du xml  où le paramètre layersvisibility est à `undefined`
> 
> ```
> <themes mini="false"> 
>     <theme id="education" url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml" name="Education et formation" collapsed="true" icon="false" layersvisibility="undefined"> 
>     </theme> 
>     <theme id="transport" url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/transport/transports.xml" name="Transport" collapsed="true" icon="false" layersvisibility="undefined"> 
>     </theme> 
>     <theme id="inventaire" url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/patrimoine/patrimoine.xml" name="Inventaire du patrimoine" collapsed="true" icon="false" layersvisibility="undefined"> 
>     </theme> 
> </themes>
> ```
> 


Bug corrigé sur la branch `develop-meg-VSR` , un oubli de ma part quand on parse l'application à l'ouverture.

**Comment by lecault** [comment]
Je viens de tester c'est bon.
