### ISSUE TITLE
Recherche une application : résultat si trouve aucune application

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#200]
Je veux chercher une application par mot clé. Je saisie un mot clé  :

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/357d99e5-12a7-4582-bf4f-862f9de12081)

S'il ne renvoie rien je n'ai pas moyen de relancer une nouvelle recherche : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/b6f01114-b921-4cde-8195-837854ea2547)

### Comportement attendu
 si pas de résultats retournés, avoir toujours la barre de recherche.

**Comment by Gaetanbrl** [comment]
Corrigé sur issue-161-rebase et visible sur https://gis.jdev.fr/mviewerstudio/index.html#
