### ISSUE TITLE
MEG-186 Import XML sans proxy

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#201]
L'import d'un XML qui n'a pas de balise proxy fait planter le parseur XML : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/40761156-06a0-4a00-ac9c-701da0d9691f)

Pour tester : 
- Sauvegarder un XML généré depuis studio
- Enlever la ligne <proxy url= >
- Réimporter

Exemple de XML : https://kartenn.region-bretagne.fr/kartoviz/demo/isochrones.xml

Cela est problématique car il est courant d'avoir des mviewer sans proxy

**Comment by Gaetanbrl** [comment]
Si tu utilises "proxy" dans ton studio c'est que tu en as besoin pour que les appels fonctionnent.
Si tu l'enlèves, ca me semble logique que ca ne fonctionne plus. Par contre si le XML n'est pas interprété ou que tu as une erreur dans la console, ce n'est pas pareil.

Est-ce donc possible d'avoir des des informations complémentaires en plus de "ne fonctionne pas" @lecault ?

- Quelles est l'erreurs ?
- Sur quelle instance tu as testée ?
- Que vois-tu qui t'indique que ca ne fonctionne pas ?

**Comment by Gaetanbrl** [comment]
Je pense que c'est à re tester maintenant @lecault.

J'ai ajouté une modification pour ne plus lire le Proxy depuis le XML (cette erreur étant survenue sur ce code).

La valeur du proxy sera toujours celle du config.json.

**Comment by lecault** [comment]
Je viens de tester ça fonctionne.
La limite est si je charge un fichier XML qui a un proxy de renseigné, cette valeur sera écrasé par la valeur par défaut du config.json.

**Comment by Gaetanbrl** [comment]
> La limite est si je charge un fichier XML qui a un proxy de renseigné

La question que je me pose est la suivante : 

Est-ce que vous connaissez des cas où le proxy du XML est différent du proxy du mviewer ? 
Si oui, quelle est la règle  ? On conserve par défaut le proxy du XML ou bien on prend toujours celui du config.json comme je le proposais jusque là ? 

(question identique posée ce jour sur Element)

**Comment by spelhate** [comment]
> > La limite est si je charge un fichier XML qui a un proxy de renseigné
> 
> La question que je me pose est la suivante :
> 
> Est-ce que vous connaissez des cas où le proxy du XML est différent du proxy du mviewer ? Si oui, quelle est la règle ? On conserve par défaut le proxy du XML ou bien on prend toujours celui du config.json comme je le proposais jusque là ?
> 
> (question un peu identique posée ce jour sur Element avant les derniers commits sur ce sujet)

Pour un nouveau projet, le proxy par défaut est celui défini dans la conf studio (configuration.json). Pour un projet existant,  on lit la valeur proxy URL du config.xml.

**Comment by spelhate** [comment]
Gestion du proxy liéé également à #186

**Comment by spelhate** [comment]
Le proxy défini dans un config.xml est bien récupéré par l'IHM.
Par contre si aucun proxy défini dans le xml importé, l'IHM affecte la valeur du proxy défini dans le config.json.
Ça ne marche donc pas. Testé sur develop-meg-vsr.

**Comment by lecault** [comment]
Je confirme. Il faudrait mettre <proxy url=""/> si pas de proxy renseigné dans le XML.

**Comment by Gaetanbrl** [comment]
> Je confirme. Il faudrait mettre si pas de proxy renseigné dans le XML.

Je ne comprend pas @lecault ?

**Comment by Gaetanbrl** [comment]
> Le proxy défini dans un config.xml est bien récupéré par l'IHM.
Par contre si aucun proxy défini dans le xml importé, l'IHM affecte la valeur du proxy défini dans le config.json.
Ça ne marche donc pas. Testé sur develop-meg-vsr.


Désolé mais je ne comprend pas.

J'importe un XML avec le proxy suivant : 

`<proxy url=""/>`

Je vois dans l'IHM que la valeur n'est pas lue, c'est ce que vous avez souhaité :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/cb5d8eb7-2c33-497c-a947-0b6a0674578e)

dans le config.json la valeur est toujours ma valeur par défaut définie dans le config.json : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/a3aeaab6-9884-4b11-85a7-714f50ec4deb)

Je sauvegarde le XML et je constate que le XML sauvegardé a toujours bien aucune valeur :

`<proxy url=""/>`

Je vérifie ensuite la valeur du config.json et il est toujours identique à la valeur par défaut :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/4f653bdb-673c-496f-a5fb-79d6d20b104d)

**Comment by Gaetanbrl** [comment]
Vous devez avoir un cas de test différent du mien (ou fichier d'entrée différent), c'est pour cela que je vais avoir besoin du détail de votre test svp (étapes, fichiers en entrée si possible, infos classiques).

**Comment by Gaetanbrl** [comment]
ok vu : 
> Par contre si aucun proxy défini dans le xml importé

... signifie également pas de balise <proxy> et non pas que la valeur de l'URL vide pour la balise proxy. Détail important pour les cas de test.

**Comment by lecault** [comment]
J'ai complété je me suis fait avoir par le code non visible par défaut

**Comment by lecault** [comment]
lié à #186. C'est bon pour moi.
