### ISSUE TITLE
MEG - VSR - Générateur de template - éjection application

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#206]
Gros bug bloquant. Impossible de tester les templates car on se fait éjecter de l'application directement. Pour reproduire, il faut créer un nouveau projet et aller jusqu'à la création d'un template sans enregistrer.

**Comment by spelhate** [comment]
A noter que lors de nos tests, nous nous sommes fait éjecter de l'application sans explications.
Si on se fait éjecter d'une application, l'application est ensuite inutilisable et il faut tout recommencer.

**Comment by Gaetanbrl** [comment]
Idem je reproduis sans lien apparent avec le fait que l'application soit déjà sauvegardée ou non.
Je pense à un problème de redirect bootstrap avec l'ancrage `data-bs-toggle`.

**Comment by Gaetanbrl** [comment]
**Correctif :**

Modification de l'interface et remplacement du bouton.

> correctif disponible / testable dans la branche https://github.com/jdev-org/mviewerstudio/tree/develop-meg-vsr

**Comment by Gaetanbrl** [comment]
Correctif à tester sur la branche develop-meg-vsr.

Modification réalisée : Ajout du `type="button"` sur les boutons d'ouverture de la modal.

E.g

`<button type="button" class="btn btn-primary">Primary</button>`
