### ISSUE TITLE
MEG - VSR - Documentation - tableau des options des composants du générateur mal formé

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#208]
![image](https://github.com/mviewer/mviewerstudio/assets/1793792/b38ec7d6-bdcd-42cc-8f42-7d65e47b7b80)

**Comment by Gaetanbrl** [comment]
Vu,

Syntaxe a utiliser avec RST / Sphinx : 

https://github.com/mviewer/mviewer/blob/1f655de1c93a614d1db20b4ba804f27927a98a8e/docs/doc_dev/custom.rst?plain=1#L12

**Comment by Gaetanbrl** [comment]
Lien de prévisualisation : 

https://delib.csm.ovh/documentation-studio/doc_user/param_data.html#interface-du-generateur-de-template

@Agath21 regarde les liste (erreurs retournées au build)
