### ISSUE TITLE
MEG - VSR - Générateur de template - changement du positionnement du panneau

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#210]
Pour reproduire :
- Créer une fiche d'information positionnée sur le panneau de droite
- Modifier en passant en panneau en bas
- Retourner au menu édition
=> On est jeté de notre projet

Souhait : s'il y a une fiche d'information personnalisé et qu'on veut changer de positionnement du panneau, avoir un message d'avertissement disant que la fiche sera vidée.

**Comment by Gaetanbrl** [comment]
En complément, je viens de refaire les cas de tests précédents, et pour le cas 9, j'ai apporté un correctif permettant le changement du panel droite / bas sans enregistrement.

L'"éjection" était liée à l'issue #206 - donc aucun lien entre le changement d'emplacement du panel et la redirection vers la page d'accueil.

**Comment by Gaetanbrl** [comment]
Correctif à tester sur develop-meg-vsr.

**Comment by lecault** [comment]
Effectivement le changement se passe bien.
Testé avec plus de 3 encarts dans le template avec succès.
