### ISSUE TITLE
MEG - VSR - Générateur de template - bug composant Iframe

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#211]
Le composant iframe - saisie libre ne fonctionne pas. Testé avec "https://data.megalis.bretagne.bzh/?siren={{code_epci}}"

**Comment by Gaetanbrl** [comment]
ok vu.

La prévisualisation fonctionne, mais pas le template final.
Erreur de syntaxe suite à l'ajout de la condition sur le type "champ unique" pre-livraison.

Correction en cours.

**Comment by Gaetanbrl** [comment]
@spelhate tu peux me dire quelle couche tu as utilisée pour avoir les EPCI ?

**Comment by spelhate** [comment]
**EPCI en Bretagne** (epci -> https://geobretagne.fr/geoserver/ign/ows)

**Comment by Gaetanbrl** [comment]
Tester avec la couche liste des EPCI sutie à un correctif : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/7230b287-b9d4-4e3d-8590-e5beba03c94e)


Autre soucis sur la hauteur et la largeur. Ici, l'iframe n'est pas visible car la hauteur n'est pas bonne et la largeur est scrollable.
Le contenu de l'Iframe semble trop important en dimension pour s'adapter au panel du template mviewer.

Avec @Agath21, nous proposons de rajouter un paramètre (non spécifié au préalable) permettant de modifier la hauteur de l'Iframe. La largeur restant définies à 100%, il ne sera pas possible de la modifier, étant limité par la taille du panel mviewer (prévu par défaut dans le fichier `mviewer.css`).

Voici le rendu avec une hauteur plus grande pour ton cas de test @spelhate :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/956ed201-f8c4-4823-9d22-284496928125)

**Comment by Gaetanbrl** [comment]
Correctif / évolution disponibles sur la branche develop-meg-vsr avec un nouveau champ CSS :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/2a60342d-5c21-4190-a059-816657a2b3e6)


![image](https://github.com/mviewer/mviewerstudio/assets/16317988/b0473628-0cab-4711-9f81-b98e315d0107)

**Comment by Gaetanbrl** [comment]
Testable, documentation en cours de mise à jour.

**Comment by lecault** [comment]
Merci ça fonctionne.

J'ai une question : dans ce cas je suis frustré de ne pas pouvoir copier la valeur saisie en exemple dans le CSS. 
Est-ce possible de mettre par défaut la valeur paramétrée et de pouvoir la modifier ?

**Comment by Gaetanbrl** [comment]
oui mais ce serait imposer une valeur pour toutes les Iframe, ce qui n'est pas souhaitable.

**Comment by Gaetanbrl** [comment]
> Est-ce possible de mettre par défaut la valeur paramétrée et de pouvoir la modifier ?

J'ai mis une valeur par défaut, mais qui n'est pas paramétrable dans la config de studio.
Tu peux cependant maintenant copier / coller la valeur ou seulement modifier la valeur par défaut : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/a2675219-028f-42ab-b748-b776b539211e)


**Modification disponible pour test.**
