### ISSUE TITLE
MEG - VSR - Générateur de template - bug composants "plusieurs champs"

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#213]
En saisissant correctement les champs dans la zone de texte et en faisant entrée, le composant n'affiche rien.
En revanche ça marche si on sélectionne une valeur suggérée.

Reproduit avec Titre et sous-titres et texte

**Comment by Gaetanbrl** [comment]
@spelhate Je viens de reproduire une issue mais qui ne semble pas correspondre à ta description.
Je peux en effet ajouter une valeur de champ qui existe en la saisissant et ne appuyant sur "Entrée" mais la prévisualisation ne fonctionne pas.

Voici le cas de test que j'ai réalisé et à utiliser pour cette issue : 

- Dans une thématique d'application, ajouter la couche "Liste des communes par EPCI"
- Ouvrir la configuration pour cette couche
- Ouvrir un template existant (ou créer un nouveau template) avec le générateur
- Ajouter un Titre
- Choisir dans la liste "A partir de plusieurs champs"
- Dans le second champ, saisir manuellement la valeur code_siren et appuyer sur la touche "Entrée"
- Voir que le champ est bien ajouté
- Cliquer sur "Prévisualiser" et voir la bonne représentation du champ
- Sauvegarder l'application et voir dans le template (via l'onglet Network du navigateur) que le template sauvegardé est correct et contient le champ saisi

**Test KO : la prévisualisation ne fonctionne pas + la syntaxe mustache ne contient pas le champ.**

**Comment by Gaetanbrl** [comment]
Cette issue semble liée au comportement natif de la librairie utilisée.

J'ai ouvert une issue pour le suivi : 
 https://github.com/lekoala/bootstrap5-tags/issues/91
 
Je pense cependant avoir trouvé un correctif (le commit suivra ce message).
