### ISSUE TITLE
MEG - VSR - Générateur de template - bug Création template avant chargement de la feature

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#214]
Le seul moyen de s'en sortir est de supprimer la couche et de recommencer la génération d'un template. C'est gênant.

**Comment by Gaetanbrl** [comment]
Je confirme, idem pour https://github.com/mviewer/mviewerstudio/issues/202.

**Comment by Gaetanbrl** [comment]
Corrigé une première fois, mais au final on a toujours le phénomène async avec une connexion plus lente.

**Comment by Gaetanbrl** [comment]
Après tests et re tests, nous n'arrivons pas à reproduire le cas d'un soucis asyncho entre les données WFS et la mise à disposition du générateur de template.

**Issue en attente dans le cas où le problème se reproduis.**

**Comment by lecault** [comment]
Je confirme, je viens de tester un cas où j'édite le template avant que la liste des styles apparaîssent j'ai quand même la liste des attributs.

**Comment by Gaetanbrl** [comment]
> Je confirme, je viens de tester un cas où j'édite le template avant que la liste des styles apparaîssent j'ai quand même la liste des attributs.

Pour toi c'est OK ou KO ?

**Comment by lecault** [comment]
Je confirme que je reproduis pas donc OK
