### ISSUE TITLE
MEG - VSR projet non enregistré physiquement (install PHP)

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#216]
Branche develop-meg-vsr
Install PHP (https://kartenn.region-bretagne.fr/mviewerstudio-jdev/)

Je créé un nouveau projet.
Je l'enregistre. J'ai un message comme quoi le fichier est sauvegardé sur le serveur mais il n'est pas sauvegardé, pas moyen de le récupérer.

Du coup, je pense que c'est un effet de bord mais la prévisualisation ne fonctionne pas.

**Comment by lecault** [comment]
> Il faut que www-data ait les droits d'écriture sur le répertoire que tu utilises pour sauvegarder les xml. Cette faiblesse existaient déjà auparavant.

C'est le cas, j'utilise le même répertoire qu'avant

**Comment by Gaetanbrl** [comment]
j'ai apporté des correctifs pour la partie PHP. En attente de retours.

**Comment by lecault** [comment]
Pas mieux

**Comment by Gaetanbrl** [comment]
ok étrange je les ai bien chez moi

**Comment by Gaetanbrl** [comment]
> Pas mieux. L'application est appelée comme ceci : xml=apps/store-dev/undefined

Est-ce possible de me partager l'erreur de la console et ta config (fichier config.json) stp ?

Avec seulement ces infos, je ne parviens pas à me faire une idée du problème ni où chercher.

Je vois seulement qu'il chercher un XML avec un identifiant spécifique et que le clic sur "modifier" ne semble pas retourner d'ID.

**Comment by lecault** [comment]
Vu avec Gaetan. Il manquait un / dans la conf
