### ISSUE TITLE
MEG - VSR - Liste - Placement des champs avec plusieurs concaténation de champ

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#217]
# Description

Lorsqu'on utilise plusieurs type liste pour une couche, l'affichage des champs avec le type "A partir d'un champ" n'est pas correct.

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/6978c4bf-afdc-4f86-9a5d-37f876a4837d)

**Comment by Gaetanbrl** [comment]
Correctif disponible et à tester sur develop-meg-vsr : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/dd72a0a8-dfa3-4090-960a-09c571337519)

**Comment by lecault** [comment]
C'est bon je clos
