### ISSUE TITLE
Générateur de template - Ajout d'un composant libre

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewerstudio#218]
### Idée d'évolution

En supplément des composants existants au sein du générateur de template, il serait intéressant d'avoir un type de composant "Personnalisé" avec une zone de saisie libre permettant de saisir du code brut comme des iframes avec des attributs avancées ou des éléments html supplémentaires (`<h3>`, `<small>`, `<i>`).

**Comment by Gaetanbrl** [comment]
Ce composant devra permettre d'ajouter un code Superset.
@lecault / @smevel pouvez-vous partager un code exemple ici réutilisable fourni par superset ?

**Comment by Gaetanbrl** [comment]
Voir la documentation Superset.
https://snum.gitlab-pages.din.developpement-durable.gouv.fr/ds/gd3ia/offre-dataviz-documentation/03-Documentation_SUPERSET_CREATEUR_ET_VISUALISATEUR/
-------

### Exemple d'intégration :


```
<html>
    <body>
        <h1>Exemple d'intégration de Superset dans une page externe</h1>
        Ceci est une page web contenant une iFrame affichant Superset<br>
        <h2>Exemple de mise en œuvre</h2>
        L'iFrame appelle la page avec les paramètres standalone=3 et show_filters=1<br>
        <iframe
            width="1200"
            height="800"
            src="https://demo.dataviz.din.developpement-durable.gouv.fr/superset/dashboard/41?standalone=3&&show_filters=1">
        </iframe><br>
    </body>
</html>
```

![image](https://github.com/user-attachments/assets/b4e88d66-6ab0-469d-a168-b37223bc1237)

**Comment by smevel** [comment]
> Ce composant devra permettre d'ajouter un code Superset. @lecault / @smevel pouvez-vous partager un code exemple ici réutilisable fourni par superset ?

tu parles d'une dataviz uniquement ou du tableau de bord entier ?

**Comment by Gaetanbrl** [comment]
> tu parles d'une dataviz uniquement ou du tableau de bord entier ?

De ce dont vous avez besoin car je n'en sais pas plus sur ce qu'il vous faut :)

**Comment by Gaetanbrl** [comment]
> https://superset-dev.geobretagne.fr/superset/dashboard/11/

Sur cet exemple @smevel je ne vois qu'un dashboard, mais pas de code intégrable dans mviewer. 
Est-ce le lien à reprendre dans une iframe pour l'intégrer ?

**Comment by lecault** [comment]
JE crois que c'est ça : https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/territoire/territoire_superset.xml

MST : https://kartenn.region-bretagne.fr/kartoviz/apps/region/territoire/templates/epci_superset.mst

**Comment by smevel** [comment]
Ce template permet de restituer le dashboard précédent :


{{#features}}
	<li class="item">
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="https://superset-dev.geobretagne.fr/superset/dashboard/11/?insee={{code_insee}}&standalone=3" allowfullscreen></iframe>
		</div>
	</li>
{{/features}}

**Comment by Gaetanbrl** [comment]
@lecault 
> https://kartenn.region-bretagne.fr/kartoviz/apps/region/territoire/templates/epci_superset.mst

Dans cet exemple je n'ai rien dans le template au clic.

**Comment by Gaetanbrl** [comment]
@smevel @lecault les infos relatives à la partie Superset sont à compléter dans #301 svp, ce sera plus simple :)

**Comment by Gaetanbrl** [comment]
https://github.com/mviewer/mviewerstudio/issues/218#issuecomment-2337304282

Pouvez-vous actualiser cet exemple ?
