### ISSUE TITLE
MEG - VSR - Générateur de templates à partir de plusieurs champs caractère nom champ doublé

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#219]
Scénario :

1. Création d'un nouveau projet
2. Ajout couche lycées
3. Création d'un template
4. Ajout d'un titre à partir de plusieurs champs
5a. Taper nom - code_rne
5b. Taper code: code_rne
6a. Dans la prévisualisation il met 2 -
6b. Dans la prévisualisation il met 2 fois code:
7. Même comportement à l'interrogation de la couche

Bug valable pour type titre, sous titre, texte.

**Comment by Gaetanbrl** [comment]
@lecault Oui j'ai vu ce bug qui est une régression suite à la correction d'un autre bug aujourd'hui.
Déjà corrigé normalement (ton issue à croisé le correctif je pense).

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/521714ca-23b7-452d-b633-23ceb227737f)

**Comment by Gaetanbrl** [comment]
@lecault par contre je ne comprend pas ces étapes : 

```
Ajout d'un titre à partir de plusieurs champs
5a. Taper nom - code_rne
5b. Taper code: code_rne
```

Tu peux me partager une capture de ce que tu as mis dans l'IHM stp ?

**Comment by lecault** [comment]
a et b sont 2 scénarios. Je confirme la correction. Je ferme.
