### ISSUE TITLE
MEG-VSR Localisation et nommage des boutons de validation non cohérente

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#221]
Le bouton valider n'est pas toujours au même endroit ça peut entraîner des erreurs.

Aussi le nommage n'est pas toujours le même.

Au niveau thématique, valider est à droite : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/e74f8524-b32d-4c24-9441-8697e487cd90)

Au niveau paramètre de la donnée c'est à gauche : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/cb959420-2bdb-474d-9351-bf1078acab38)

Idem dans le générateur de template : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/def8d998-d2de-4551-8c2e-84cb8883801c)

Proposition
Enregistrer toujours à gauche
Annuler toujours à droite (fermer ne laisse pas forcément entendre que les modifications seront perdues)

**Comment by Gaetanbrl** [comment]
Je vais faire le tour et vérifier / modifier si besoin ;)

**Comment by Gaetanbrl** [comment]
Modifications disponibles, disponible pour test : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/04e901e9-1ff5-4231-8086-de7b96061619)


![image](https://github.com/mviewer/mviewerstudio/assets/16317988/92237a4a-ac93-4df8-b5df-a79c080a9acc)

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/b77724b2-c415-4c0f-b957-7f915ff0282e)

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/3e6f23f6-ee36-4d7e-8484-f068e2a639d9)

**Comment by spelhate** [comment]
Ok pour moi
