### ISSUE TITLE
MEG - VSR prévisualisation application publiée

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#223]
Scénario :

1. Je créé une application
2. J'ajoute une couche
3. je publie l'application
4. je prévisualise

=> La couche n'est pas visible dans la légende comme ci-dessous : l'option Ne pas afficher la donnée dans la légende est coché sans aucune action de ma part

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/30430d89-dd36-4d02-9627-9a96507bf26b)

**Comment by Gaetanbrl** [comment]
Je reproduis.
En mode avancé, l'option est cochée par défaut : 

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/96028b2c-5a02-4906-ab53-c6841930fc48)

**Comment by lecault** [comment]
> En mode avancé, l'option est cochée par défaut :

Ah j'ai pas ça dans mon cas. J'ajoute une couche à un projet en mode avancé, c'est décoché.

**Comment by Gaetanbrl** [comment]
>  J'ajoute une couche à un projet en mode avancé, c'est décoché.

par ajout tu veux dire import XML ou nouveau projet ?

**Comment by Gaetanbrl** [comment]
Dans tous les cas @lecault j'ai vu un truc qui n'allait pas, peux-tu re tester stp ?

**Comment by lecault** [comment]
> > J'ajoute une couche à un projet en mode avancé, c'est décoché.
> 
> par ajout tu veux dire import XML ou nouveau projet ?

Je commence un nouveau projet en mode avancé, j'ajoute une couche la case n'est pas cochée.

**Comment by Gaetanbrl** [comment]
Bon, le soucis vient du fait que showintoc est un boolean.

Si il est vrai, alors c'est affiché dans la TOC.

Le soucis c'est que ce n'est pas une valeur logique avec la checkbox qui indique "Masqer ?" Si c'est cocher (checkbox vraie) alors il faut détermier l'inverse et avoir une valeur `showintoc="false"` dans le XML.

La checkbox devrait plutôt être "Afficher dans la toc", comme ca on est cohérent entre la valeur de la checkbox et la valeur dans le XML.

**Comment by Gaetanbrl** [comment]
Correctif poussé pour déterminer l'inverse d'une condition vraie contenant une valeur fausse ou vraie : 

```
            let showintoc = !(layer?.showintoc || layer?.showintoc == undefined);
            $("#frm-layer-showintoc").prop("checked", showintoc);
```

**Comment by spelhate** [comment]
C'est bon pour moi.
