### ISSUE TITLE
MEG - VSR Documentation - avertissements au build

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#224]
Le build de la doc mentionne 3 avertissements :

- [x] index.rst:41: WARNING: toctree contains reference to nonexisting document 'doc_tech/migration_notes'
- [x] doc_tech/migration.rst: WARNING: document isn't included in any toctree
- [x] doc_tech/install.rst:40: WARNING: Could not lex literal_block as "json". Highlighting skipped.

**Comment by Gaetanbrl** [comment]
D'autres warning viennent d'être corrigés. Je ne vois plus de warning liés à des problèmes de syntaxe RST.
Les warning restants sont des informations en lien avec l'environnement de build, comme la configuration native de la doc ou à la version sphinx.

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/3ea51c3e-3fde-4284-aa86-69e6a0ec96d7)
