### ISSUE TITLE
MEG - VSR Documentation - ajustements

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#225]
### Orthographe

- [x] doc_user/param_appli.html#champs-principaux :  l’utilisateur sera redirigée => l’utilisateur sera redirigé
- [x] doc_user/param_appli.html#fonds-de-plan : checkboxe => checkbox
- [x]  doc_user/param_data.html#ajouter-une-donnee-depuis-ces-parametres (ses paramètres)
- [x] doc_user/param_data.html#parametrer-ses-donnees : Séléctionner => Sélectionner
- [x] doc_user/param_data.html#onglet-general : Attributions => Attribution
- [x] doc_user/param_data.html#onglet-general : la données s’affiche=> la donnée s’affiche
- [x] doc_user/param_data.html#id1 : Valeur à partir d’un champs -> Valeur à partir d’un champ
- [x] doc_user/param_data.html#interface-du-generateur-de-template :  configurer la fiche d’information et ces composants -> configurer la fiche d’information et ses composants
- [x] doc_user/param_data.html#interface-du-generateur-de-template : synthaxe => syntaxe ; nom_du_champs => nom_du_champ
- [x] doc_user/publication.html#publier-une-application-depuis-le-studio : le nom saisie => le nom saisi
- [x] doc_user/gestion_appli.html#gerer-son-application : en haut à droit => en haut à droite

### Précisions

- [x] doc_user/accueil.html#construire-son-application : Les 2 choix proposés sont relatifs à l'import d'un projet existant. renommer construire son application en ouvrir une application existante. Précision que pour modifier et supprimer ça dépend des droits relatifs au projet.
- [x] doc_user/accueil.html#etapes-de-creation : Renommer en création d'un nouveau projet
- [x] doc_user/param_data.html#ajouter-une-donnee : préciser que c'est uniquement dans le mode création de thématique
- [x] doc_user/param_data.html#ajouter-une-donnee-depuis-un-catalogue : préciser avant par mot clé qu'on peut ajouter une donnée de 2 façons. Pour l'ajout d'une adresse, préciser que le serveur sera ajouter à la liste des serveurs pour la session uniquement.
- [x] doc_user/publication.html#publier-son-application : "télécharger le fichier .XML pour le déposer ensuite sur un serveur en production' ça n'a plus lieu d'être avec le bouton publier votre application
- [x] doc_user/gestion_appli.html#gerer-les-versions : il manque la signification des actions

La partie 3 de install_python.html est incomplète sur la partie configuration frontend
Exemple de paramètres non décrits : 
- [x] "public_folder"	: "prod" dans "mviewer_short_url"
- [x]  publish_url  :	"?config=apps/prod/{{config}}.xml"
- [x] external_themes : { used: true, url: "https://geobretagne.fr/minicatalog/csv" }
- [x] proxy
- [x] studio-title

### Corrections

- [x] doc_user/param_appli.html#options-de-la-carte : il faut enlever le badge mode avancé pour Revenir à l'étendue initiale
- [x] doc_user/param_appli.html#fonds-de-plan : Identifiant technique de la couche est un paramètre obligatoire
- [x] doc_user/param_appli.html#recherche-mode-avance : Recherche visible en mode simple
- [x] doc_user/param_data.html#option-importer-une-thematique-externe : pour accéder au paramétrage d'une couche importé, il faut cliquer sur l'engrenage et non Ajouter des données.
- [x] doc_user/param_data.html#onglet-options-avancees : mettre à jour l'image
- [x] doc_user/param_data.html#onglet-options-avancees : Affichage de la données seulement sur la carte => Ne pas afficher la donnée dans la légende
- [x] doc_user/param_data.html#onglet-options-avancees : Type de légende : possibilité de mettre une légende personnalisée vers un fichier image (via une URL).
- [x] doc_user/param_data.html#ajouter-des-composants-a-la-fiche-dinformation : cliquez sur valider pour l’ajouter => cliquez sur enregistrer pour l’ajouter
- [x] doc_user/param_data.html#enregistrer-la-fiche-d-information : bouton « Valider » => bouton « Enregiostrer »
- [x] doc_user/gestion_appli.html#gerer-son-application : mise d'un badge mode avancée devant options. d'ailleurs il faut préciser qu'il n'est visible que si l'application a été enregistrée.
- [x] doc_user/gestion_appli.html#creer-une-version : une description à la version et valider => une description à la version et enregistrer
- [x] doc_tech/install.html#installer-mviewerstudio : il faut renommer cette catégorie en Installer mviewerstudio avec PHP. Et mettre un avertissement qu'avec ce type d'installation, on ne disposera pas de toutes les fonctionnalités (@Gaetanbrl : écrit dans la section note de migration).

### Production
partie manquante : https://delib.csm.ovh/documentation-studio/doc_tech/install_python.html#mettre-en-production-mviewerstudio  et disponible ici : https://raw.githubusercontent.com/mviewer/mviewerstudio/develop/docs/doc_tech/install_python.rst

### Note (@lecault)
J'ai complété les remarques de Sébastien, il y a des modifications à effectuées qui sont indépendantes du marché en cours et qui pourront être faites par la suite.

**Comment by Agath21** [comment]
> doc_user/gestion_appli.html#gerer-les-versions : il manque la signification des badges

C'est expliqué dans cette rubrique : doc_user/gestion_appli.html#gerer-la-publication-d-une-application
