### ISSUE TITLE
MEG - VSR Filtre dynamique KO

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#229]
Le filtre dynamique ne fonctionne plus, on ne récupère pas la liste des champs : 

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/cd876743-7ddc-4ff1-8e72-c9d2c928f963)

Scénario : 

1. J'ajoute la couche des lycées
2. Je fais sur l'onglet Filtre dynamique

**Comment by Gaetanbrl** [comment]
Idem, à vérifier avec @Agath21
ce n'est pas dans le scope de nos modifications pour cette prestation (MEG) mais on va vérifier.

**Comment by Gaetanbrl** [comment]
Modifications apportées dans la branche develop-meg-vsr.

**Comment by lecault** [comment]
c'est bon
