### ISSUE TITLE
MEG - VSR : filtre statique KO

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#230]
Le filtre statique ne fonctionne plus : on ne récupère plus la liste des champs 

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/d094ccc2-b595-4df6-a225-5092f3c81deb)

Scénario : 
1. J'ajoute la couche des lycées
2. Je passe en mode avancé
3. Je fait un filtre statique

**Comment by Gaetanbrl** [comment]
@Agath21 à voir.

**Comment by Gaetanbrl** [comment]
* ce n'est pas dans le scope de nos modifications mais on va vérifier.

**Comment by lecault** [comment]
ça fonctionne dans la branche master https://kartenn.region-bretagne.fr/mviewerstudio

**Comment by spelhate** [comment]
> Vu dans le code, la fonction showFields qui permettait de réaliser un template à partir des champs (ancien template generator) a été supprimée.

Pourquoi cette fonction a été supprimée ?

**Comment by Gaetanbrl** [comment]
Erreur de ma part lorsque j'ai supprimé le code lié à l'ancien système de personnalisation. Je pensais en effet que toute la fonction n'était dédiée qu'à l'ancien système de personnalisation des templates mais finalement, pas uniquement. J'ai donc remis la fonction et supprimé ce qui n'était plus utile.
