### ISSUE TITLE
MEG - VSR lien vers une légende personnalisée ne fonctionne pas

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#231]
Scénario :

1. Je créé une application
2. J'ajoute une donnée exemple lycées
3. Je passe en mode avancé
4. Je vais dans l'onglet Options avancées de paramètres de la donnée
5. Je saisi un lien vers une légende personnalisée
=> L'information n'est pas conservée

**Comment by Gaetanbrl** [comment]
A vérifier mais nous ne pensons pas avoir modifié cette fonctionnalité.
Test à réaliser dans la version latest (branche master) pour prise en compte ou non dans la VSR.

**Comment by lecault** [comment]
ça fonctionne dans la branche master https://kartenn.region-bretagne.fr/mviewerstudio

**Comment by lecault** [comment]
C'est bon
