### ISSUE TITLE
MEG - VSR Ouvrir un projet existant : statut en ligne pas dans la bonne couleur

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#233]
Lorsque je veux ouvrir un projet existant, les projets En ligne apparaissent en violet alors qu'ils devraient être en orange : 

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/259db741-ca65-4a51-8b9a-ec8dd4a800b6)

**Comment by lecault** [comment]
Bon je l'ai eu en orange à d'autres reprises...

**Comment by Gaetanbrl** [comment]
Corrigé dans branche vsr via 35896dceedd95a72462d56638e412feb1fe81a4e

**Comment by lecault** [comment]
C'est bon pour moi
