### ISSUE TITLE
MEG - VSR : comportement création nouvelle application après enregistrement

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#237]
Scénario : 

1. J'ouvre une application existante (ou je suis sur une application en cours de création)
2. Je retourne à l'accueil en enregistrant mon application
3. Je créé un nouveau projet
4. Le bouton Supprimer apparaît comme si l'application aurait été enregistrée (ce qui n'est pas le cas)

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/26b4ff51-ae1d-4da3-9a9a-0904a18fd9fd)

**Comment by Gaetanbrl** [comment]
Vu, reproduis et modification poussée.

**Comment by lecault** [comment]
Vu je clos
