### ISSUE TITLE
MEG - VSR générateur de template : type liste non conservé

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#238]
Scénario : 
1. Je créé une nouvelle application
2. J'ajoute une donnée de type liste (exemple liste communes EPCI)
3. Je prévisualise ça fonctionne bien
4. Je ferme en enregistrant
5. Je réouvre mon application
6. Je prévisualiser : le champ liste n'apparaît pas à l'interrogation
7. Je vais voir au niveau du générateur de template, le template n'apparaît plus

**Comment by lecault** [comment]
lié à #239

**Comment by lecault** [comment]
J'ai toujours le soucis : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/20963b07-53df-42e2-b586-7bd9149c1537)

**Comment by Gaetanbrl** [comment]
vu reproduis.
Je me penche dessus.
