### ISSUE TITLE
MEG - VSR générateur de template : disparition du template

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#239]
Scénario : 
1. Je créé une application
2. J'ajoute une donnée et je fais un template
3. Je ferme et j'enregistre
4. Je réouvre l'application
5. Je vais sur le générateur de template
6. Le template n'apparait plus dans l'interface graphique (il est bien créé sur le serveur)

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/b99ce659-7cb1-423e-9027-5606147672f3)

**Comment by lecault** [comment]
Je complète : le template est interprété comme un template externe : 

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/a2ea9a0a-ce06-4cfa-98af-a61f18645c56)

**Comment by Gaetanbrl** [comment]
Vu, reproduis.

je viens de pousser un correctif, je n'ai pas poussé les tests encore;

**Comment by lecault** [comment]
ok c'est bon
