### ISSUE TITLE
Ajout de nouveaux paramètres

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#24]
En complément de #23

- Activation de la géolocalisation
- Paramètre de home url
- Paramètre export vers studio

**Comment by bchartier** [comment]
@spelhate : pas sûr de comprendre la partie "Paramètre export vers studio". Tu fais référence à quoi ?

**Comment by spelhate** [comment]
Il s'agit d'un bouton depuis mviewer qui permet d'envoyer depuis mviewer le config.xml courant vers mviewerstudio pour modification.
Ainsi depuis studio, il est possible de transmettre une conf xml vers mviewer,
depuis mviewer, il est possible de transmette la conf xml courante à studio.

**Comment by bchartier** [comment]
Ok. Je vois de quoi il s'agit.

**Comment by lecault** [comment]
Lié à #157
