### ISSUE TITLE
MEG - VSR enregistrement si clic thématique

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#240]
Scénario : 
1. J'ouvre un projet existant
2. Je vais sur thématiques et données
3. Je vais sur le menu d'édition de thématique
4. Je ne fais rien je clic sur enregistrer
5. Une nouvelle version est créée sur le serveur

Ce n'est pas bloquant mais ça surcharge le nombre de version. Pourquoi le comportement a évolué ?

**Comment by Gaetanbrl** [comment]
j'ai rajouté un enregistrement au clic sur "enregistrer".
Il permet de réaliser une sauvegarde intermédiaire des thématiques et des templates.
Inconvénient, le clic sur enregistrer est possible alors qu'aucune modification n'a encore été réalisée.
La question se pose surtout sur l'utilité d'un bouton enregistrer et annuler alors qu'aucune action n'a été réalisée.

Je crois que c'est le comportement historique ?

**Comment by Gaetanbrl** [comment]
Mais il est nouveau (depuis hier) d'avoir une action d'enregistrement. le mieux serait de ne pas en avoir si on a rien modifié, mais je crois qu'on avait déjà abordé ce sujet, il avait été considéré comme une évolution.

**Comment by lecault** [comment]
Le fait d'avoir un enregistrement par clic sur enregistrer une thématique va poluer le recensement des versions.

Je me suis fait la réflexion hier qu'en fait le bouton devrait s'appeler Valider plutôt qu'enregistrer.
Pour ma part, je souhaite revenir au comportement précédent : enregistrement si clic sur enregistrer ou au premier changement de page.

**Comment by Gaetanbrl** [comment]
@lecault tu n'as pas vraiment répondu à ma question, mais je viens de pousser un autre comportement. Ce que j'ai testé me convient et permet de ne pas réaliser de nouvelle version si on a pas de modification réalisée (la différence est non nulle).

Est-ce que tu peux tester à nouveau et me dire si pour toi ce comportement est mieux ?

**Comment by Gaetanbrl** [comment]
> Je me suis fait la réflexion hier qu'en fait le bouton devrait s'appeler Valider plutôt qu'enregistrer.

Tu nous avais pas demandé d'harmoniser tous les boutons ? C'était Valider ou Enregistrer qu'on devait mettre je ne sais plus ?

**Comment by lecault** [comment]
> @lecault tu n'as pas vraiment répondu à ma question, mais je viens de pousser un autre comportement. Ce que j'ai testé me convient et permet de ne pas réaliser de nouvelle version si on a pas de modification réalisée (la différence est non nulle).

Oui tu as bien répondu à ma demande d'harmonisation je te confirme, c'est juste une réflexion à froid qui ne rentre pas dans le cadre de la VSR. Enregistrer => enregistre l'application. Valider => valide la page courante. Laisse comme cela.

**Comment by lecault** [comment]
J'ai relevé un soucis si on a plusieurs thématiques, le comportement ne fonctionne que sur la dernière thématique.
Exemple ici : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/1a0fe8c9-b6b9-44ad-80e2-0b58aecc4577)


Cas 1 : 
- Je clique sur SCOT je fais une modif 
- Aucun message

Cas 2 : 
- Je clique sur SCOT aucune modif
- Aucun message

Cas 3 : 
- Je clique sur SCOT je fais une modif 
- Je clique sur VN aucune modif
- Un message dit qu'il a bien enregistré les modifs

Cas 4 : 
- Je clique sur SCOT aucune modif
- Je clique sur VN je fais une modif
- Un message dit qu'il a bien enregistré les modifs

Cas 5 : 
- Je clique sur SCOT aucune modif
- Je clique sur VN aucune modif
- Un message dit qu'il n'y a pas de modif

Pour moi mineur.

**Comment by Gaetanbrl** [comment]
je viens de voir ton retour Loïc (si possible, bien penser à mettre à jour le tableau projet dans la bonne colonne)

**Comment by Gaetanbrl** [comment]
@lecault a détailler pour chaque étape si possible : 

>  je fais une modif

Quelle modification ?

> aucune modif

Tu cliques sur "Enregistrer" ou "annuler" ?

**Comment by Gaetanbrl** [comment]
## Testé suite au message de @lecault 

Je créé 2 thématiques :

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/8f9961ad-e91f-443f-8315-eabaa566d77b)


Cas 1 :

* Je clique sur A et je fais une modif (je coche "Déroulée par défaut")
* J'ai bien un message
* TEST OK

Cas 2 :

* Je clique sur A et ne réalise aucune modif
* Aucun message
* TEST OK

Cas 3 :

* Je clique sur A je fais une modif 
* Je dois cliquer sur Enregistrer pour valider la modif
* Je vois un message indiquant que le XML est bien enregistré
* Je clique sur B et ne réalise aucune modif
* Je clique sur Enregistrer
* Un message m'indique qu'il n'y a rien a modifier
* TEST OK

Cas 4 :

* Je clique sur A aucune modif + Enregistre
* Un message me dit qu'il n'y a rien à enregistrer
* Je clique sur B je fais une modif + clic sur "Enregistrer"
* Un message me dit qu'il y a bien eu une sauvegarde
* TEST OK

Cas 5 :

* Je clique sur A  aucune modif + clic sur Annuler
* Je ne vois pas de message => OK c'est normal
* Je clique sur B aucune modif + clic sur Enregistrer
* Un message dit qu'il n'y a pas de modif
* TEST OK

Où est le comportement qui n'est pas correspondant à tes attentes @lecault ?

**Comment by lecault** [comment]
Effectivement je ne constate plus de soucis. c'est bon pour moi.
