### ISSUE TITLE
MEG VSR - Version affichée dans les crédits à actualiser

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#241]
Actuellement on MviewerStudio | Licence GPL-3.0 | Version 3.1

il faudrait : Actuellement on MviewerStudio | Licence GPL-3.0 | Version 3.2

**Comment by Gaetanbrl** [comment]
Vu, idem pour la version mviewer compatible

**Comment by lecault** [comment]
Juste une remarque : il y a un bouton fermer qui ne sert à rien => à supprimer

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/31a3d6b5-55fd-42fe-bba3-373f74af8fe1)

**Comment by spelhate** [comment]
Pour info, avec la modification effectuée sur les crédits, le footer qui embarque le bouton fermer est sorti de la div modal-content.
Il doit y avoir un </div> de trop

**Comment by Gaetanbrl** [comment]
je ne l'avais pas vu ce bouton tiens !

**Comment by lecault** [comment]
C'est bon je ferme
