### ISSUE TITLE
MEG - VSR problèmes de redémarrage de service

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#246]
J'ai des soucis pour redémarrer mon service. J'y arrive au bout d'un moment.

A spécifier...

**Comment by Gaetanbrl** [comment]
J'ai déjà parlé de ce problème rencontré avec gunicorn. De mon côté je constate qu'il ne démarre pas en raison de git qui est encore en train d'écrire.

Plusieurs restart permettent de démarrer le service prod.

C'est documenté ici :

https://github.com/jdev-org/mviewerstudio/blob/c852adce6d3b54ce3d4bda463c2639363b0ad981/docs/doc_tech/install_python.rst?plain=1#L272-L275

**Comment by Gaetanbrl** [comment]
Il manque peut être des options pour un stop / restart propre. A voir selon la doc gunicorn (@spelhate si tu as une idée ?)

**Comment by spelhate** [comment]
Peut être qu'il faut stopper le process git avant de restart ?

**Comment by spelhate** [comment]
Sinon en adaptant le service avec ce type de paramétrage : 
```sh
[Service]
ExecStart=/path/to/executable
Restart=on-failure
RestartSec=1s
```

**Comment by Gaetanbrl** [comment]
On va regarder avec @pierrejego, merci pour les suggestions @spelhate

**Comment by lecault** [comment]
Un retour d'expérience sur ce sujet.
Sur la version installée sur GéoBretagne, je n'arrivais pas à redémarrer le service avec les données existantes (4,5 organismes avec plusieurs applications). 
Pour que ça marche :
- Sauvegarde des dossiers /store et /prod
- Vidage des dossiers
- Relance du service OK
- Recopie du contenu précédent

ça semble fonctionner.

**Comment by Gaetanbrl** [comment]
Je remarque qu'au démarrage via gunicorn, le service semble faire 2x la création de l'app Flask. Cela créé peut être un problème d'accès aux fichiers Git encore ouvert (accès concurrents)...

**Comment by Gaetanbrl** [comment]
J'ai facilement reproduis le comportement / erreurs via l'ajout de workers supplémentaires dans le fichier .service (daemon).

Chaque worker rejoue la création du register et le repositionnement de chaque application sur la derniere version (git reset --hard). Si un worker est en cours de reset et qu'un autre tente de faire la même opération, alors le second passe sur un .lock du premier et génère une erreur.

Pourtant d'un point de vue file-system, l'opération attendue sera bien faite par le worker qui a posé le lock.

Soit on utilise qu'un worker soit on gère l'erreur.

J'ai donc rajouté une gestion d'erreur pour le git lock.

Le lock rencontré apparaîtra dans le fichier de log (voir #300) mviewerstudio.log.

Suite à cette modification, je n'ai pas reproduis d'erreur au restart avc 3 workers.

**Comment by lecault** [comment]
Depuis la PR #320 je n'ai pas eu de souci de redémarrage du service
