### ISSUE TITLE
MEG - VSR bug suppression template

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewerstudio#247]
Il n'est pas possible de supprimer un template fraîchement créé. L'enregistrment consécutif à la suppression indique 'aucune modification à enregistrer'.
Contournement : quitter l'application, recharger l'application et supprimer le template

**Comment by Gaetanbrl** [comment]
Pouvez-vous indiquer les étapes pour reproduire ?

**Comment by Gaetanbrl** [comment]
Vu / reproduit.
Correctif disponible pour test sur `develop-meg-vsr`.

**Comment by lecault** [comment]
Pour moi c'est bon, pas vu d'effets de bord
