### ISSUE TITLE
MEG Suppression couche et url

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#249]
> Ref #205 

Sur la nouvelle version Mégalis

Scénario : 
1. Je créé une application
2. J'ajoute une couche
3. Je clique sur prévisualiser
4. Je supprime la couche
5. L'url est modifiée https://geobretagne.fr/mviewer/#

Et j'ai le même comportement dans une url publiée : 
- Ouvrir cette url https://geobretagne.fr/mviewer/#prod/region_bretagne/test
- Supprimer la couche => l'url est modifiée

Alors ça ne bloque pas l'utilisation c'est juste embêtant pour recharger une application.

**Comment by Gaetanbrl** [comment]
Précision : 

L'org de l'URL de preview n'est pas bon uniquement si on clic sur le bouton : 

- Preview dans le wizzard section "Publication"
- Preview lors du clic sur "Prévisualiser" depuis la liste de toutes les application dans la page d'accueil


Le bouton Prévisualiser à côté de "Enregistrer"  et de "Supprimer" pour une application fonctionne bien.

**Comment by Gaetanbrl** [comment]
Précision : 

Le problème survient dans mviewer quand on supprime une couche de la TOC.

**Comment by lecault** [comment]
C'est pas lié au # ?

**Comment by Gaetanbrl** [comment]
Reproduis sur le XML par défaut du mviewer dans une instance locale.

Test sur geobretagne : 

- URL longue -> OK
https://geobretagne.fr/mviewer/?config=/apps/adresse/config.xml#

- URL courte -> KO
https://geobretagne.fr/mviewer/#

Cette issue n'est donc pas liée à studio. A reporter dans mviewer et à clore ici.

**Comment by Gaetanbrl** [comment]
Je clos, issue reportée ici : 

https://github.com/mviewer/mviewer/issues/764
