### ISSUE TITLE
MEG lien de prévisualisation application publiée

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#250]
Scénario : 
- Je créé une application
- Je publie l'application => le statut est en ligne
- Je clique sur prévisualiser votre application dans la page de pûblication
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/93bd2fe6-61e5-46b7-bc4e-d25ac1bb0a2c)

Le lien renvoi une erreur. Exemple d'url générée https://geobretagne.fr/mviewer/#prod/R%C3%A9gion%20Bretagne/vn
L'organisme dans l'url n'est pas encodé

**Comment by Gaetanbrl** [comment]
Précision :

L'org de l'URL de preview n'est pas bon uniquement si on clic sur le bouton :

Preview dans le wizzard section "Publication"
Preview lors du clic sur "Prévisualiser" depuis la liste de toutes les application dans la page d'accueil
Le bouton Prévisualiser à côté de "Enregistrer" et de "Supprimer" pour une application fonctionne bien.

**Comment by Gaetanbrl** [comment]
Correctif disponible sur develop-meg.

**Comment by lecault** [comment]
C'est bon
