### ISSUE TITLE
MEG - Adaptation dockerfile et docker compose

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#252]
# description

Les scripts docker nécessitent d'être revus en lien avec #205 

# Proposition d'architecture

N'hésitez-pas à commenter / faire des remarques sur ce schéma (qui n'est pas parfait je pense)

![image](https://github.com/mviewer/mviewerstudio/assets/16317988/0164a27f-ae3c-4236-b7f5-e9f5e09c2bba)

**Comment by spelhate** [comment]
L'image Docker de la branche develop ne se fabrique plus correctement : 
https://github.com/mviewer/mviewerstudio/actions/runs/5345266244/jobs/9690712130

**Comment by Gaetanbrl** [comment]
Je viens de tester un script docker pour générer l'image du studio sur une branche issue-252: 

https://github.com/mviewer/mviewerstudio/blob/issue-252/docker/README.md

il reste des tests pour voir le fonctionnement des volumes, et des adaptations pour voir si l'image actuelle peut être utilisée en l'état avec le script docker-compose (sinon faire les adaptations).

**Comment by Gaetanbrl** [comment]
Réalisé via #277
