### ISSUE TITLE
DOC - dev - inversion script SH et change URL

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#257]
# Description

Cette issue liste et corrige les erreurs suivantes : 

- inversion paramètres dans la doc pour l'install via script SH
- Manque dans les prérequis python3-venv (ou bien à rajouter dans le script)

**Comment by lecault** [comment]
Pour info, on a fait des modifs : https://mviewerstudio.readthedocs.io/fr/latest/doc_tech/install_python.html

**Comment by Gaetanbrl** [comment]
> Le script n'est pas le même que celui ci 

Le script a la racine ne semble plus bon.
La doc d'install scriptée renvoi vers le bon script /srv/python.
Je pense que celui à la racine peut être supprimé.
Si besoin il sera retrouvé dans les commits github.
