### ISSUE TITLE
Ajout paramètre maxzoom

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#285]
Suite à une remarque d'un partenaire, on trouve intéressant d'avoir la possibilité d'ajouter le seuil de zoom maximal (maxzoom) dans studio en vue avancée.

**Comment by Gaetanbrl** [comment]
@lecault l'idée est de déplacé de la vue "simple" vers la vue "avancé" ?

**Comment by lecault** [comment]
Il n'est pas présent dans studio.
L'idée serait de l'ajouter en vue avancé au niveau des options de carte : 

![image](https://github.com/user-attachments/assets/189b8acd-c0a1-4a6e-8a90-83cabaac393e)
