### ISSUE TITLE
Filtre dynamique non fonctionnel

### ISSUE THREAD

**Issue by lvinsonneau** [mviewer/mviewerstudio#291]
Bonjour,
je tente de mettre un **filtre dynamique** sur une couche de données Mégalis présente sur GéoBretagne (en l'occurrence [celle-ci](https://geobretagne.fr/geonetwork/srv/fre/catalog.search#/metadata/2fedae07-6854-47b1-a370-98153d4edde7)).
Le filtre souhaité est le suivant : **service_coffre_fort=OUI**
Or dans la fenêtre, il ne me propose que la valeur "NON" alors qu'il y a bien des valeurs à "OUI" dans la BDD : 
![image](https://github.com/mviewer/mviewerstudio/assets/2498403/f60407cf-b172-44fa-80e2-d6a6205d8a15)

Il y a peut-être qqchose que je n'ai pas capté ?

**Comment by Gaetanbrl** [comment]
Lorsque l'IHM des filtres dynamiques est construite, ces étapes sont réalisées : 

- appel de toutes les features de la couche
- lecture de l'attribut sélectionné (ici service_coffre_fort)
- création d'une liste de valeurs uniques pour ce champ

Mais je vois qu'il y a une limite de 100 (maxFeatures) dans l'appels de la requête de toutes les features. Si les 100 premières features n'ont qu'une valeur NON, alors la valeur OUI ne sera pas identifiées et non visible.

On peut considérer que c'est un bug @lvinsonneau car il ne devrait pas y avoir de limite pour lister toutes les valeurs. Il est aussi possible que ce comportement était un choix délibérée (ca ne me dit rien mais on ne sait jamais) car un appel sur une couche large va ralentir le fonctionnement le temps de récupérer et traiter toutes les features (comme ici car cette couche à + de 6 000 entités).

Dans ce cas de figure, je conseil de saisir manuellement une valeur dans le champs `Valeur(s) sélectionnée(s)`. 
En premier comme alternative à ce comportement et pour éviter des appels larges :

> valider la saisie avec un appuie sur la touche "entrée" du clavier ou en cliquant en dehors du champ

![dynFilter](https://github.com/mviewer/mviewerstudio/assets/16317988/74f5f844-9a02-4b2c-95c1-97ebc92c0107)


**On reste d'accord que ce comportement n'est pas tellement souhaitable car cela oblige l'utilisateur à connaître toutes les valeurs possibles comme lors de la saisie dans le XML... ce qui n'a pas dans sens dans studio car les valeurs ne sont que partiellement complète dans ce cas (pas pratique).**

**Comment by Gaetanbrl** [comment]
> ça n'empêche que mon besoin reste de filtrer et ce, même s'il y a 6000 entités

Comme indiqué en bas de mon commentaire :

> On reste d'accord que ce comportement n'est pas tellement souhaitable car cela oblige l'utilisateur à connaître toutes les valeurs possibles comme lors de la saisie dans le XML... ce qui n'a pas dans sens dans studio car les valeurs ne sont que partiellement complète dans ce cas (pas pratique).

**Comment by lvinsonneau** [comment]
OKèche, mais moi pas réussir avec solution de contournement... alors moi retourne au mviewer en attendant

**Comment by Gaetanbrl** [comment]
@lvinsonneau 

> mais moi pas réussir avec solution de contournement... alors moi retourne au mviewer en attendant

Je comprend qu'il y a un bug sur l'utilisation de ce champ en plus d'une limite MAX qui est un autre sujet.

Est-ce que tu peux m'en dire plus stp sur ce que tu vois stp ?

**Comment by lvinsonneau** [comment]
yes, on peut se faire un partage d'écran via element ?

**Comment by Gaetanbrl** [comment]
vu avec @lvinsonneau, l'alternative fonctionne bien.
Le ticket reste ouvert et sera à fermer après vérification du fonctionnement lié à la suppression du MAXFEATURES.
