### ISSUE TITLE
URL générée pour une application : organisme court

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#293]
**Problématique**

Avec le déploiement de mviewerstudio sur GéoBretagne, nous avons remarqué que si l'intitulé de l'organisme du partenaire est long, cela génère une URL à rallonge.

Exemples : 
en preview : https://geobretagne.fr/mviewer/#store/agence_d_attractivite_et_de_developpement_de_redon_agglomeration/75ff09939d07/preview/541360d6-e117-11ee-bcde-005056909889
en prod : https://geobretagne.fr/mviewer/#prod/agence_d_attractivite_et_de_developpement_de_redon_agglomeration/test

**Proposition de solution**

Pouvoir choisir via un paramètre dans la conf json d'utiliser plutôt l'organisme court. Ce qui donnerai dans notre cas : https://geobretagne.fr/mviewer/#prod/redon_attractivite/test

**Comment by Gaetanbrl** [comment]
A voir pour changer le champ utilisé : 
https://github.com/mviewer/mviewerstudio/blob/ce784ff603c1c99a479c75c99f9fdd16e3319c21/srv/python/mviewerstudio_backend/utils/login_utils.py#L17

**Comment by lecault** [comment]
C'est bien ici, j'ai remplacé sec-orgname par sec-org et ça fonctionne.

Maintenant ce que je cherche à faire c'est de passer cette valeur en paramètre.

J'ai ajouté dans le service :
     Environment="TYPE_ORG=sec_org"

Et j'ai essayé comme ci-dessous de récupérer la variable dans le login_utils.py mais ça ne marche pas.

        typeorg = current_app.config["TYPE_ORG"]
        orgname = request.headers.get(typeorg)

**Comment by Gaetanbrl** [comment]
> Maintenant ce que je cherche à faire c'est de passer cette valeur en paramètre.

Pourquoi ne pas toujours prendre le nom court ?

**Comment by lecault** [comment]
Je me dis que ça peut dépendre de la façon de saisir le nom.

On pourrait le mettre par défaut et mettre en commentaire la valeur du nom long si ça te semble pas pertinent de mettre un paramètre.

**Comment by Gaetanbrl** [comment]
Je n'ai pas trop d'avis sur la question, le nom court est également utile pour la création des répertoires sur le serveur (mieux que le nom long, plus simple).
A la rigueur, on peut mettre un contrôle sur le nombre de caractère et afficher le nom long dans un cas et le nom court dans l'autre.
Si on ne met que le nom court ca me convient, je ne sais pas ce qu'en penserai les utilisateurs cela dit.

**Comment by lecault** [comment]
Voici un exemple de ce que ça donne en nom normal : 

![image](https://github.com/mviewer/mviewerstudio/assets/5269430/54ec5790-08df-484c-8e13-07441b1daca9)


Du coup, je penche pour mettre mon court par défaut. Je fais une PR

**Comment by Gaetanbrl** [comment]
> Du coup, je penche pour mettre mon court par défaut. Je fais une PR

👍
