### ISSUE TITLE
Ajout du niveau groupe dans l'arborescence

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#294]
Dans studio, il n'est actuellement pas possible d'ajouter le niveau <group> dans le panneau des thématiques.

![image](https://github.com/user-attachments/assets/7d07b10c-86af-48e9-a690-1fcf4eff1e5e)

Dev intéressant à faire en parallèle de l'issue #145

**Comment by LPoin** [comment]
En PR Draft pour test -> https://github.com/mviewer/mviewerstudio/pull/330
Une passe graphique et d'opti est en court.
