### ISSUE TITLE
Composant Superset

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewerstudio#301]
> Lié à https://github.com/mviewer/mviewerstudio/issues/218

> Via @lecault @smevel 

### Description

Dans le générateur de template,
Il est demandé de pouvoir ajouter un contenu provenant de Superset.

### Détails fonctionnels

Le composant est à sélectionner et paramétrer comme les autres.

### Détails techniques

- Documentation [Superset](https://snum.gitlab-pages.din.developpement-durable.gouv.fr/ds/gd3ia/offre-dataviz-documentation/03-Documentation_SUPERSET_CREATEUR_ET_VISUALISATEUR/)
- Exemple de [contenu réalisé avec Superset ](https://superset-dev.geobretagne.fr/superset/dashboard/11/)
- Exemple d'intégration dans un [template mviewer](https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/territoire/territoire_superset.xml)  - ([code du template](https://kartenn.region-bretagne.fr/kartoviz/apps/region/territoire/templates/epci_superset.mst))

![image](https://github.com/user-attachments/assets/5ec53280-5c92-4490-af10-3af2e02a943d)

**Comment by Gaetanbrl** [comment]
A noter que pour Superset, Il n'est pas nécessaire d'avoir un composant libre pour modifier la propriété `src`.

Si on reprend le code du template mis en exemple vous pouvez utiliser le composant "Iframe" qui permettra d'avoir une saisie libre sur la source de l'iframe :

![image](https://github.com/user-attachments/assets/2962b92d-3b69-4596-b81d-c366077482b1)

Fournira : 

```
      <iframe src="https://superset.bretagne.bzh/superset/dashboard/pepci/?siren=&amp;standalone=3" style="height:500px; width:100%" frameborder="0" name="demo">
        </iframe>
```

**Comment by Gaetanbrl** [comment]
@lecault qu'avez-vous besoin de plus pour que cela fonctionne avec Superset ?

**Comment by lecault** [comment]
Je viens de tester ici : https://kartenn.region-bretagne.fr/kartoviz-dev/#public/public/superset

Effectivement, l'option iframe rempli le contrat.

Je ne suis pas sur qu'il faille plus à ce stade du projet. A confirmer avec @smevel
