### ISSUE TITLE
Légende disparue suite à publication d'une application

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#323]
Scénario : 

1. Je créé une application avec une donnée
2. Je la prévisualise : tout s'affiche bien
3. Je publie cette application
4. Je la prévisualise : la légende ne s'affiche plus

Note : la légende ne s'affiche pas sur la version publiée aussi. Exemple : https://geobretagne.fr/mviewer/#prod/rb/issue

Le problème se déclenche lors de la prévisualisation d'une application publiée.

![image](https://github.com/user-attachments/assets/faf142fc-c61d-4d9b-8b7d-8a131a6fa9ed)

**Comment by lecault** [comment]
J'ai trouvé : en fait je ne sais pas pour quelle raison, le fait de publier met l'option showintoc à false : 

![image](https://github.com/user-attachments/assets/2797a0ed-370b-458c-b51b-a8786b0a4a99)

**Comment by Gaetanbrl** [comment]
La prise en compte / sauvegarde de ce paramètre n'est pas correcte.

**Comment by Gaetanbrl** [comment]
> J'ai trouvé : en fait je ne sais pas pour quelle raison, le fait de publier met l'option showintoc à false :

L'affectation / prise en compte de la valeur par défaut n'était pas correcte. Le premier correctif de cette issue n'était pas complet.
Le dernier correctif est à tester.

**Comment by lecault** [comment]
ça semble bon dans la version de la PR330.

**Comment by Gaetanbrl** [comment]
> ça semble bon dans la version de la PR330.

Correctif validé via #330. Je clos.
