### ISSUE TITLE
Modification du nom d'une couche puis ajout de couche : perte d'informations

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#336]
Scénario : 
- J'ajoute une couche
- Je modifie le nom de cette couche
- J'ajoute une nouvelle couche
- Dans ma thématique, les 2 couches pointent sur la dernière couche ajoutée

![image](https://github.com/user-attachments/assets/5fa95bde-b3a0-4e0b-b95f-115dad504da3)

Probablement en lien avec l'issue #324

**Comment by Gaetanbrl** [comment]
Reproduit - analyse en cours

**Comment by Gaetanbrl** [comment]
> Je modifie le nom de cette couche

Cette étape n'est pas utile et fausse l'analyse.

Ces nouvelles étapes pour reproduire mettent en avant un comportement avec la classe "active" :

1. ajouter la couche des lycée
2. ouvrir le menu des paramètres d'une couche
3. Fermer la modal sans rien faire
4. Ajouter une autre couche
5. Voir que la couche active (les lycée) change de nom et prend le nom de la nouvelle données

**Comment by Gaetanbrl** [comment]
Pour améliorer la gestion de la navigation, il convient de supprimer l'état "actif" d'une donnée lorsque la modal n'est pas ouverte.

La donnée en blanc (active), ne devrait pas l'être dans cet écran puisque rien n'est en cours sur cette donnée : 

![image](https://github.com/user-attachments/assets/19e846a5-264b-4069-a716-92f6fb26a6f7)

**Comment by Gaetanbrl** [comment]
On voit également que plusieurs layers peuvent être active, ce qui ne devrait pas être le cas : 

![image](https://github.com/user-attachments/assets/c2dbafb8-0d31-4384-bc51-b40714d8bb6b)

**Comment by Gaetanbrl** [comment]
Correctif à tester dans la PR en cours https://github.com/mviewer/mviewerstudio/pull/330

**Comment by Gaetanbrl** [comment]
@lecault à fermer si c'est bon pour toi
