### ISSUE TITLE
L'option réduire le panneau des thématiques ne fonctionne pas correctement

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#339]
Si on sélectionne l'option réduire le panneau des thématiques au démarrage, le bandeau des thématiques n'est pas réduit que l'on ai des groupes ou pas.

![image](https://github.com/user-attachments/assets/cd5f5bf5-d220-4f8e-8505-c0a6c8e1d93d)

Résultat sur la version en développement : 

![image](https://github.com/user-attachments/assets/9565e283-4ad2-434d-bbbb-aba0e15905df)

Résultat sur la version 4.1 : 

![image](https://github.com/user-attachments/assets/755577bb-d98b-4f5d-b47a-6f7138f9387a)

**Comment by lecault** [comment]
A tester même XML dans une version ancienne de mviewer.

**Comment by lecault** [comment]
Je n'ai plus le souci sur la version de dev. A fermer une fois le merge #330 effectué.

**Comment by Gaetanbrl** [comment]
> A fermer une fois le merge https://github.com/mviewer/mviewerstudio/pull/330 effectué.

Je clos. Merci @lecault
