### ISSUE TITLE
Déplacement d'une donnée via drag and drop : impossibilité de récupérer les informations WFS

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewerstudio#344]
Sur la version en cours de développement.

Scénario : 
- J'ajoute une donnée
- Je l'ouvre et vérifie que l'on récupère bien les styles
- Je créé un groupe
- Je déplace la donnée dans un groupe
- J'ouvre la donnée, je ne récupère pas le style et ne peut pas faire de fiche d'informations

Voici l'erreur dans la console : 

![image](https://github.com/user-attachments/assets/cb24c22f-73b2-480b-b290-1225cafd9173)

En lien avec la PR #330

**Comment by Gaetanbrl** [comment]
Après analyse,
Il semble que la notion de groupe n'existe pas lors de la récupération / affichage des champs d'une donnée :

![image](https://github.com/user-attachments/assets/259d7d01-0423-4138-875b-5403574e462d)

**Comment by Gaetanbrl** [comment]
idem pour la méthode `showStyle`

Correctif apporté (voir commit précédent) : 

- Utiliser et adapter une méthode standard (déjà existante) `mv.getLayerById ` pour récupérer une layer par son ID
- adapter cette méthode pour parcourir les groupes également

**Comment by lecault** [comment]
Résolu dans la PR330. Fermeture de l'issue une fois la PR mergée.

**Comment by Gaetanbrl** [comment]
Correctif validé. Je clos.
