### ISSUE TITLE
Aide dans le formulaire d'édition d'une couche

### ISSUE THREAD

**Issue by bchartier** [mviewer/mviewerstudio#67]
Il serait bon d'ajouter des textes d'aide dans le formulaire d'édition d'une couche.
Visiblement, la bonne manière de faire avec les formulaire Bootstrap 3 c'est d'utiliser un `help-block`: https://bootstrapdocs.com/v3.3.5/docs/css/#forms-help-text
J'ai peur que cela ne prenne trop de place dans l'IHM.

Mon but était de mettre un texte qui explique à quels attributs de mviewer fait référence chaque champ du formulaire. Est-ce que cela vous paraît jouable d'intégrer un help-block ou est-ce que vous avez une autre proposition ? Par exemple : mettre un petit texte à côté du titre du champ sur la même ligne ?

**Comment by bchartier** [comment]
Pour illustrer ma dernière proposition :
![GéoBretagne_mviewer_studio](https://user-images.githubusercontent.com/2361255/77303473-5230bd00-6cf3-11ea-9e87-5f37a67927c8.jpg)

**Comment by Gaetanbrl** [comment]
Pour tes propositions je préfère la seconde ;) 

Sinon, autre proposition, placer un icône d'aide et afficher une tooltip au survol de l'icône : 
![image](https://user-images.githubusercontent.com/16317988/77307572-cbcba980-6cf9-11ea-800c-071fd9b42c5d.png)

[Doc tooltip Bootstrap 3](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_tooltip&stacked=h)

**Comment by bchartier** [comment]
On pourrait imaginer la combinaison des deux (si on a besoin que le texte affiché en permanence soit court et éventuellement afficher un complément au survol) ?

**Comment by Gaetanbrl** [comment]
Oui ca peut être intéressant.
Je pense qu'il serait aussi bien d'y ajouter un lien vers un endroit d'une doc.

**Comment by spelhate** [comment]
J'ai une préférence pour la proposition **help-block** avec éventuellement la **tooltip** si nécessaire.

**Comment by bchartier** [comment]
> J'ai une préférence pour la proposition help-block avec éventuellement la tooltip si nécessaire.

@spelhate : tu n'a pas peur que cela fasse des formulaires très longs ?

**Comment by bchartier** [comment]
Je vais faire un test sur page complète du formulaire des couches sur une branche pour que vous jugiez sur pièce. Je mettrai des copies d'écran dans ce ticket.

**Comment by spelhate** [comment]
Merci @bchartier

**Comment by lecault** [comment]
Dans la dernière version de studio des tooltip ont été ajoutés : 
![image](https://github.com/mviewer/mviewerstudio/assets/5269430/1015968c-bc73-4077-b25a-02e9655ff5a5)

ça répond à la demande je pense ?

**Comment by spelhate** [comment]
Oui.
