### ISSUE TITLE
MviewerStudio / GeoNetwork 3.8 accès au catalogue ?

### ISSUE THREAD

**Issue by mvadin** [mviewer/mviewerstudio#75]
La recherche dans le catalogue GéoGrandEst ne fonctionne plus.
La plateforme GéoGrandEst utilise maintenant Geonetwork 3.8.

Config :

            "csw" : [
                {
                    "title" : "Catalogue GéoGrandEst",
                    "url": "https://www.geograndest.fr/geonetwork/srv/fre/csw",
                    "baseref": "https://www.geograndest.fr/geonetwork/srv/eng/catalog.search?node=srv#/metadata/"
                }
            ]

L'exception est la suivante :

<?xml version="1.0" encoding="UTF-8"?>

<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">

  <ows:Exception exceptionCode="NoApplicableCode">

    <ows:ExceptionText>Raised exception while searching metadata : java.lang.IllegalArgumentException: Error when parsing spatial filter (version: 1.1.0):&lt;ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"&gt;&#xD;

  &lt;ogc:And&gt;&#xD;

    &lt;ogc:And&gt;&#xD;

      &lt;ogc:Or&gt;&#xD;

        &lt;ogc:PropertyIsLike wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

          &lt;ogc:PropertyName&gt;Type&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;dataset&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsLike&gt;&#xD;

        &lt;ogc:PropertyIsLike wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

          &lt;ogc:PropertyName&gt;Type&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;series&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsLike&gt;&#xD;

      &lt;/ogc:Or&gt;&#xD;

    &lt;/ogc:And&gt;&#xD;

    &lt;ogc:Or&gt;&#xD;

      &lt;ogc:Or&gt;&#xD;

        &lt;ogc:PropertyIsEqualTo matchCase="true"&gt;&#xD;

          &lt;ogc:PropertyName&gt;Title&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;lyc&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsEqualTo&gt;&#xD;

        &lt;ogc:PropertyIsEqualTo matchCase="true"&gt;&#xD;

          &lt;ogc:PropertyName&gt;AlternateTitle&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;{query}&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsEqualTo&gt;&#xD;

        &lt;ogc:PropertyIsEqualTo matchCase="true"&gt;&#xD;

          &lt;ogc:PropertyName&gt;Identifier&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;{query}&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsEqualTo&gt;&#xD;

        &lt;ogc:PropertyIsEqualTo matchCase="true"&gt;&#xD;

          &lt;ogc:PropertyName&gt;ResourceIdentifier&lt;/ogc:PropertyName&gt;&#xD;

          &lt;ogc:Literal&gt;{query}&lt;/ogc:Literal&gt;&#xD;

        &lt;/ogc:PropertyIsEqualTo&gt;&#xD;

      &lt;/ogc:Or&gt;&#xD;

      &lt;ogc:And&gt;&#xD;

        &lt;ogc:Or&gt;&#xD;

          &lt;ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

            &lt;ogc:PropertyName&gt;Title&lt;/ogc:PropertyName&gt;&#xD;

            &lt;ogc:Literal&gt;{query}*&lt;/ogc:Literal&gt;&#xD;

          &lt;/ogc:PropertyIsLike&gt;&#xD;

          &lt;ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

            &lt;ogc:PropertyName&gt;AlternateTitle&lt;/ogc:PropertyName&gt;&#xD;

            &lt;ogc:Literal&gt;{query}*&lt;/ogc:Literal&gt;&#xD;

          &lt;/ogc:PropertyIsLike&gt;&#xD;

          &lt;ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

            &lt;ogc:PropertyName&gt;Abstract&lt;/ogc:PropertyName&gt;&#xD;

            &lt;ogc:Literal&gt;{query}*&lt;/ogc:Literal&gt;&#xD;

          &lt;/ogc:PropertyIsLike&gt;&#xD;

          &lt;ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

            &lt;ogc:PropertyName&gt;Subject&lt;/ogc:PropertyName&gt;&#xD;

            &lt;ogc:Literal&gt;{query}*&lt;/ogc:Literal&gt;&#xD;

          &lt;/ogc:PropertyIsLike&gt;&#xD;

          &lt;ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!"&gt;&#xD;

            &lt;ogc:PropertyName&gt;OrganisationName&lt;/ogc:PropertyName&gt;&#xD;

            &lt;ogc:Literal&gt;{query}*&lt;/ogc:Literal&gt;&#xD;

          &lt;/ogc:PropertyIsLike&gt;&#xD;

        &lt;/ogc:Or&gt;&#xD;

      &lt;/ogc:And&gt;&#xD;

    &lt;/ogc:Or&gt;&#xD;

  &lt;/ogc:And&gt;&#xD;

&lt;/ogc:Filter&gt;. Error is: org.apache.jcs.access.exception.InvalidArgumentException:  Errors parsing filter:

org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 15; cvc-complex-type.2.4.b: The content of element 'ogc:And' is not complete. One of '{"http://www.opengis.net/ogc":comparisonOps, "http://www.opengis.net/ogc":spatialOps, "http://www.opengis.net/ogc":logicOps, "http://www.opengis.net/ogc":Function}' is expected.

org.xml.sax.SAXParseException; lineNumber: 57; columnNumber: 17; cvc-complex-type.2.4.b: The content of element 'ogc:And' is not complete. One of '{"http://www.opengis.net/ogc":comparisonOps, "http://www.opengis.net/ogc":spatialOps, "http://www.opengis.net/ogc":logicOps, "http://www.opengis.net/ogc":Function}' is expected.</ows:ExceptionText>

  </ows:Exception>

</ows:ExceptionReport>

**Comment by lecault** [comment]
Bonjour Mickael,

Je confirme nous avons le même soucis à la région où nous sommes sur un GN 3.10 non GéOrchestra.

**Comment by spelhate** [comment]
Pour info je reproduis la même erreur depuis le mapfishapp région grand est en cherchant une couche.
![image](https://user-images.githubusercontent.com/1793792/79314116-a1889880-7f01-11ea-84f0-b3435d2d5a58.png)

**Comment by mvadin** [comment]
je viens d'ouvrir un ticket chez C2C.

**Comment by mvadin** [comment]
C2C indique qu'ils vont porter une correction dans GeOrchestra : 
cf : https://github.com/georchestra/georchestra/pull/3031

**Comment by bchartier** [comment]
Si @lecault a le même souci avec un Geonetwork non geOrchestra le problème de vient pas de geOrchestra, si ?

**Comment by spelhate** [comment]
Ca ressemble effectivement à une régression geonetwork.
Peut être que le fix peut galement être effectué côté client (post request) dans mapfishapp et mviewer ?

**Comment by bchartier** [comment]
@lecault @mvadin : quel est le statut de ce ticket ? Est-ce qu'il faut toujours faire quelque chose ?

**Comment by lecault** [comment]
A la région nous n'avons plus le soucis.

**Comment by bchartier** [comment]
Merci pour ta réponse rapide.
@mvadin : j'attends ta réponse pour voir quelle suite donner au ticket.

**Comment by mvadin** [comment]
@lecault : quelles actions ont été faites chez vous ? on est toujours en GN3.8.2 + Mviewerstudio3.1 
Le problème est toujours d'actualité

**Comment by lecault** [comment]
On est passé en GN 3.10.1 et on est pas branché sur GeOrchestra.

**Comment by lecault** [comment]
Je viens de réussir à ajouter une donnée du grand est. Je ferme.
