### ISSUE TITLE
Intégrer un proxy par defaut

### ISSUE THREAD

**Issue by RemiDesgrange** [mviewer/mviewerstudio#76]
Actuellement dans les backends php et python, il n'y a pas d'implémentation pour `/proxy?url=foo` devrait-t-on en fournir un (sachant que c'est 4 lignes de code max dans les deux cas) afin qu'on ait un environnement complet en dehors de geOrchestra ?

**Comment by spelhate** [comment]
Ca rendrait service à beaucoup de gens. Merci pour la proposition.

**Comment by RemiDesgrange** [comment]
Je vais faire une PR en ce sens

**Comment by bchartier** [comment]
@RemiDesgrange : est-ce que tu avais un pull request dans ce sens finalement ?

**Comment by lecault** [comment]
Pour moi c'est bon, un proxy a été ajouté avec une whitelist.
